
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.ceshi.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.fml.event.lifecycle.FMLClientSetupEvent;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.common.ForgeSpawnEggItem;
import net.minecraftforge.api.distmarker.Dist;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Items;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.BlockItem;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.client.renderer.item.ItemProperties;

import net.mcreator.ceshi.procedures.Yssp_sxProcedure;
import net.mcreator.ceshi.procedures.Ysrqa5Procedure;
import net.mcreator.ceshi.procedures.Ysrqa4Procedure;
import net.mcreator.ceshi.procedures.Ysrqa3Procedure;
import net.mcreator.ceshi.procedures.Ysrqa2Procedure;
import net.mcreator.ceshi.procedures.Ysrqa1Procedure;
import net.mcreator.ceshi.procedures.Ysrqa0Procedure;
import net.mcreator.ceshi.procedures.YdyhdltsxProcedure;
import net.mcreator.ceshi.procedures.FumoquanpinzhizhiProcedure;
import net.mcreator.ceshi.item.ZzjsItem;
import net.mcreator.ceshi.item.ZzjllItem;
import net.mcreator.ceshi.item.ZziyousongshikuaiItem;
import net.mcreator.ceshi.item.ZziyousongshiduanpianItem;
import net.mcreator.ceshi.item.ZziyousongshiItem;
import net.mcreator.ceshi.item.ZyjslItem;
import net.mcreator.ceshi.item.ZyjsItem;
import net.mcreator.ceshi.item.ZuishengzijingItem;
import net.mcreator.ceshi.item.ZuishengsuixieItem;
import net.mcreator.ceshi.item.ZuishengkuaiItem;
import net.mcreator.ceshi.item.ZuishengduanpianItem;
import net.mcreator.ceshi.item.ZszstItem;
import net.mcreator.ceshi.item.ZszsjItem;
import net.mcreator.ceshi.item.ZstkjItem;
import net.mcreator.ceshi.item.ZstjItem;
import net.mcreator.ceshi.item.ZsspItem;
import net.mcreator.ceshi.item.ZsqItem;
import net.mcreator.ceshi.item.ZshjtItem;
import net.mcreator.ceshi.item.ZshjjItem;
import net.mcreator.ceshi.item.ZsgItem;
import net.mcreator.ceshi.item.ZsfItem;
import net.mcreator.ceshi.item.ZscItem;
import net.mcreator.ceshi.item.ZizizaihejintaoItem;
import net.mcreator.ceshi.item.ZiziyousongshisuixieItem;
import net.mcreator.ceshi.item.ZizgaoItem;
import net.mcreator.ceshi.item.ZizaizuantaoItem;
import net.mcreator.ceshi.item.ZizaizuanshijianItem;
import net.mcreator.ceshi.item.ZizaitiejianItem;
import net.mcreator.ceshi.item.ZizaitiejiaItem;
import net.mcreator.ceshi.item.ZizaiqiaoItem;
import net.mcreator.ceshi.item.ZizaihejinjianItem;
import net.mcreator.ceshi.item.ZizaifuItem;
import net.mcreator.ceshi.item.ZizaichuItem;
import net.mcreator.ceshi.item.ZhzhenyinhedaletouItem;
import net.mcreator.ceshi.item.ZhuangmanlajidelajitongItem;
import net.mcreator.ceshi.item.ZhongkouweitiedingItem;
import net.mcreator.ceshi.item.ZhongguizhongjudedaimaItem;
import net.mcreator.ceshi.item.ZhjslItem;
import net.mcreator.ceshi.item.ZhjsItem;
import net.mcreator.ceshi.item.ZhapiandingzhengshiItem;
import net.mcreator.ceshi.item.ZhangquanzhezhinangItem;
import net.mcreator.ceshi.item.ZhaiquanItem;
import net.mcreator.ceshi.item.ZfgItem;
import net.mcreator.ceshi.item.YyanziyueliangchangpianItem;
import net.mcreator.ceshi.item.YxaxgItem;
import net.mcreator.ceshi.item.YuzhousuipianItem;
import net.mcreator.ceshi.item.YuansujingtiItem;
import net.mcreator.ceshi.item.YuanshiyuanpeiItem;
import net.mcreator.ceshi.item.YuanshiqiaoItem;
import net.mcreator.ceshi.item.YuanshijianItem;
import net.mcreator.ceshi.item.YuanshigaoItem;
import net.mcreator.ceshi.item.YuanshifuItem;
import net.mcreator.ceshi.item.YuanshifItem;
import net.mcreator.ceshi.item.YuanshichutouItem;
import net.mcreator.ceshi.item.YuanshiItem;
import net.mcreator.ceshi.item.YsspItem;
import net.mcreator.ceshi.item.YsrzspsxItem;
import net.mcreator.ceshi.item.Ysrz0Item;
import net.mcreator.ceshi.item.YsrqspItem;
import net.mcreator.ceshi.item.YsjfrItem;
import net.mcreator.ceshi.item.YsjbfpkItem;
import net.mcreator.ceshi.item.YsfcItem;
import net.mcreator.ceshi.item.YoudianqiqiaodedaimaItem;
import net.mcreator.ceshi.item.YiyinhedaletouItem;
import net.mcreator.ceshi.item.YiyimuguoshiItem;
import net.mcreator.ceshi.item.YishijiemugunItem;
import net.mcreator.ceshi.item.YishijiecunzheItem;
import net.mcreator.ceshi.item.YibangrenzhinangItem;
import net.mcreator.ceshi.item.YhjslItem;
import net.mcreator.ceshi.item.YhjsItem;
import net.mcreator.ceshi.item.YhdltyidieItem;
import net.mcreator.ceshi.item.YdggzItem;
import net.mcreator.ceshi.item.YdfmsItem;
import net.mcreator.ceshi.item.XzcfyxwzdItem;
import net.mcreator.ceshi.item.XixiangyuzhiyuanItem;
import net.mcreator.ceshi.item.Xiwangdeyitian011Item;
import net.mcreator.ceshi.item.XinyuejinshuItem;
import net.mcreator.ceshi.item.XingjidaletouItem;
import net.mcreator.ceshi.item.XinghuiItem;
import net.mcreator.ceshi.item.XingchenItem;
import net.mcreator.ceshi.item.XiaodengwupinItem;
import net.mcreator.ceshi.item.XiaodaimolaItem;
import net.mcreator.ceshi.item.XiantiaoqiangItem;
import net.mcreator.ceshi.item.XiangdanganlaoItem;
import net.mcreator.ceshi.item.WuxiandiguidedaimaItem;
import net.mcreator.ceshi.item.WuqiezhihuiguangItem;
import net.mcreator.ceshi.item.Wuqie5Item;
import net.mcreator.ceshi.item.Wuqie4Item;
import net.mcreator.ceshi.item.Wuqie3Item;
import net.mcreator.ceshi.item.Wuqie2Item;
import net.mcreator.ceshi.item.WufengjianItem;
import net.mcreator.ceshi.item.WmoladaiItem;
import net.mcreator.ceshi.item.WeizhiyepianItem;
import net.mcreator.ceshi.item.WawanxiangwuchangtouItem;
import net.mcreator.ceshi.item.WanshinangItem;
import net.mcreator.ceshi.item.TiaoguozhangItem;
import net.mcreator.ceshi.item.TezhidieyingqiItem;
import net.mcreator.ceshi.item.Teshukuijia01Item;
import net.mcreator.ceshi.item.TashanglvtuchangpianItem;
import net.mcreator.ceshi.item.TaikongmanbuchangpianItem;
import net.mcreator.ceshi.item.SzzssjItem;
import net.mcreator.ceshi.item.SzzskjItem;
import net.mcreator.ceshi.item.SzzsjItem;
import net.mcreator.ceshi.item.SztjItem;
import net.mcreator.ceshi.item.SzsjtieItem;
import net.mcreator.ceshi.item.SzqItem;
import net.mcreator.ceshi.item.SzkjtieItem;
import net.mcreator.ceshi.item.SzhjsjItem;
import net.mcreator.ceshi.item.SzhjkjItem;
import net.mcreator.ceshi.item.SzhjjItem;
import net.mcreator.ceshi.item.SzgItem;
import net.mcreator.ceshi.item.SzfItem;
import net.mcreator.ceshi.item.SzcItem;
import net.mcreator.ceshi.item.SzbfzsshjsjItem;
import net.mcreator.ceshi.item.SuijiwupinItem;
import net.mcreator.ceshi.item.Suiji1shijianItem;
import net.mcreator.ceshi.item.SsjzszsItem;
import net.mcreator.ceshi.item.Sshenhudezhufu013Item;
import net.mcreator.ceshi.item.SshengjijlzsshjwpItem;
import net.mcreator.ceshi.item.SsanbamiantouItem;
import net.mcreator.ceshi.item.SjzszsshjItem;
import net.mcreator.ceshi.item.SjzstItem;
import net.mcreator.ceshi.item.SjzshjItem;
import net.mcreator.ceshi.item.SjbcqItem;
import net.mcreator.ceshi.item.ShxjdltItem;
import net.mcreator.ceshi.item.ShqwyhdltItem;
import net.mcreator.ceshi.item.ShqwfnjItem;
import net.mcreator.ceshi.item.ShiwutsslmItem;
import net.mcreator.ceshi.item.ShilianchouItem;
import net.mcreator.ceshi.item.ShenshenghuabanItem;
import net.mcreator.ceshi.item.ShenmiliheItem;
import net.mcreator.ceshi.item.ShengzhangkuaiItem;
import net.mcreator.ceshi.item.ShengzhangduanpianItem;
import net.mcreator.ceshi.item.ShengzhangbifeisuixieItem;
import net.mcreator.ceshi.item.ShengzhangbifeiItem;
import net.mcreator.ceshi.item.ShengjizuanshejinItem;
import net.mcreator.ceshi.item.ShengjizizaizuanItem;
import net.mcreator.ceshi.item.ShengjizizaitieItem;
import net.mcreator.ceshi.item.ShengjizizaihejItem;
import net.mcreator.ceshi.item.ShengjijlzswpItem;
import net.mcreator.ceshi.item.ShengjijltiewpItem;
import net.mcreator.ceshi.item.ShengjijlhjwpItem;
import net.mcreator.ceshi.item.ShcbzxItem;
import net.mcreator.ceshi.item.ShanbianzhichenItem;
import net.mcreator.ceshi.item.SanyuezhufuItem;
import net.mcreator.ceshi.item.SHJwupinItem;
import net.mcreator.ceshi.item.RyzssjItem;
import net.mcreator.ceshi.item.RyzsshjsjItem;
import net.mcreator.ceshi.item.RyzsjItem;
import net.mcreator.ceshi.item.RyttItem;
import net.mcreator.ceshi.item.RytsjItem;
import net.mcreator.ceshi.item.RytjItem;
import net.mcreator.ceshi.item.RyqItem;
import net.mcreator.ceshi.item.RyjsItem;
import net.mcreator.ceshi.item.RyjllItem;
import net.mcreator.ceshi.item.RyhjtItem;
import net.mcreator.ceshi.item.RyhjsjItem;
import net.mcreator.ceshi.item.RyhjjItem;
import net.mcreator.ceshi.item.RygItem;
import net.mcreator.ceshi.item.RyfItem;
import net.mcreator.ceshi.item.RycItem;
import net.mcreator.ceshi.item.RuzstItem;
import net.mcreator.ceshi.item.RranyuanmanaoItem;
import net.mcreator.ceshi.item.RanyuansuixieItem;
import net.mcreator.ceshi.item.RanyuankuaiItem;
import net.mcreator.ceshi.item.RanyuanduanpianItem;
import net.mcreator.ceshi.item.QyhxshilianItem;
import net.mcreator.ceshi.item.QyhxItem;
import net.mcreator.ceshi.item.QycxItem;
import net.mcreator.ceshi.item.QwyzzmItem;
import net.mcreator.ceshi.item.QwymzjItem;
import net.mcreator.ceshi.item.QwybtzdypjItem;
import net.mcreator.ceshi.item.QwxyzqItem;
import net.mcreator.ceshi.item.QwxbzsqItem;
import net.mcreator.ceshi.item.QwwxntdmjItem;
import net.mcreator.ceshi.item.QwtldhyItem;
import net.mcreator.ceshi.item.QwtcjlbptbgItem;
import net.mcreator.ceshi.item.QwsmclItem;
import net.mcreator.ceshi.item.QwqskxjxtItem;
import net.mcreator.ceshi.item.QwqcxxmxItem;
import net.mcreator.ceshi.item.QwlbtdgclItem;
import net.mcreator.ceshi.item.QwkwzjItem;
import net.mcreator.ceshi.item.QwjzyjItem;
import net.mcreator.ceshi.item.QwhdlzItem;
import net.mcreator.ceshi.item.QwggzfenlieBItem;
import net.mcreator.ceshi.item.QwggzfenlieAItem;
import net.mcreator.ceshi.item.QwflybItem;
import net.mcreator.ceshi.item.QuxgjibingItem;
import net.mcreator.ceshi.item.QiwuheisenlinggzItem;
import net.mcreator.ceshi.item.QiwuchongwangItem;
import net.mcreator.ceshi.item.QinlaodezhexueItem;
import net.mcreator.ceshi.item.Qhzllh4Item;
import net.mcreator.ceshi.item.Qhzllh2Item;
import net.mcreator.ceshi.item.QhzlhItem;
import net.mcreator.ceshi.item.Qhmbmlys02Item;
import net.mcreator.ceshi.item.Qhmbmlys01Item;
import net.mcreator.ceshi.item.QhmbmlItem;
import net.mcreator.ceshi.item.QgdysjItem;
import net.mcreator.ceshi.item.QQuHangZhoullhItem;
import net.mcreator.ceshi.item.PosuimengyingItem;
import net.mcreator.ceshi.item.PengkeluodejingshenItem;
import net.mcreator.ceshi.item.MzsjItem;
import net.mcreator.ceshi.item.Mzsj3Item;
import net.mcreator.ceshi.item.Mzsj2Item;
import net.mcreator.ceshi.item.MolachutouItem;
import net.mcreator.ceshi.item.MmolapeiziwupinItem;
import net.mcreator.ceshi.item.MmolajianItem;
import net.mcreator.ceshi.item.MmolagaoItem;
import net.mcreator.ceshi.item.MmolafuItem;
import net.mcreator.ceshi.item.MmolachanItem;
import net.mcreator.ceshi.item.Mmola01Item;
import net.mcreator.ceshi.item.MllpzsItem;
import net.mcreator.ceshi.item.MllpwzItem;
import net.mcreator.ceshi.item.MllphjItem;
import net.mcreator.ceshi.item.MllpItem;
import net.mcreator.ceshi.item.MljnbItem;
import net.mcreator.ceshi.item.MengyingItem;
import net.mcreator.ceshi.item.MeiyouzhushidaimaItem;
import net.mcreator.ceshi.item.MaoxianjiazhinangItem;
import net.mcreator.ceshi.item.MaoxianjiadejingyanItem;
import net.mcreator.ceshi.item.ManyuejinshuItem;
import net.mcreator.ceshi.item.LuanqibazaodedaimaItem;
import net.mcreator.ceshi.item.Ljtg02Item;
import net.mcreator.ceshi.item.Ljtg01Item;
import net.mcreator.ceshi.item.LiulangzhezhinangItem;
import net.mcreator.ceshi.item.LiulangzhedejingyanItem;
import net.mcreator.ceshi.item.LijsItem;
import net.mcreator.ceshi.item.LaoshiItem;
import net.mcreator.ceshi.item.LajslItem;
import net.mcreator.ceshi.item.LajitongzunyanItem;
import net.mcreator.ceshi.item.LajitongsuipianItem;
import net.mcreator.ceshi.item.LajiItem;
import net.mcreator.ceshi.item.KongyuezhufuItem;
import net.mcreator.ceshi.item.KongyuejinshuItem;
import net.mcreator.ceshi.item.KkuijiaceshiItem;
import net.mcreator.ceshi.item.KjjltItem;
import net.mcreator.ceshi.item.Kaifaqiangzhi01Item;
import net.mcreator.ceshi.item.JlzsItem;
import net.mcreator.ceshi.item.JlzaItem;
import net.mcreator.ceshi.item.JlqItem;
import net.mcreator.ceshi.item.JlmoItem;
import net.mcreator.ceshi.item.JlliangItem;
import net.mcreator.ceshi.item.JlkjzsItem;
import net.mcreator.ceshi.item.JlkjhjItem;
import net.mcreator.ceshi.item.JljzsItem;
import net.mcreator.ceshi.item.JljtieItem;
import net.mcreator.ceshi.item.JljslItem;
import net.mcreator.ceshi.item.JlgItem;
import net.mcreator.ceshi.item.JlfItem;
import net.mcreator.ceshi.item.JlcItem;
import net.mcreator.ceshi.item.JlbjItem;
import net.mcreator.ceshi.item.JjljxjhjItem;
import net.mcreator.ceshi.item.JiuchanzhiyuanxianItem;
import net.mcreator.ceshi.item.JiuchanzhiyuangaoItem;
import net.mcreator.ceshi.item.JinzhimolaItem;
import net.mcreator.ceshi.item.Jinguangbaodi01Item;
import net.mcreator.ceshi.item.JingqueyouyadaimaItem;
import net.mcreator.ceshi.item.JijiuchanzhiyuanItem;
import net.mcreator.ceshi.item.JianransuixieItem;
import net.mcreator.ceshi.item.JianmushengfaqiItem;
import net.mcreator.ceshi.item.JianlaokuaiwupinItem;
import net.mcreator.ceshi.item.JianlaohuangyuItem;
import net.mcreator.ceshi.item.JianlaoduanpianItem;
import net.mcreator.ceshi.item.JianglimaoxianjiajingyanItem;
import net.mcreator.ceshi.item.JiangliliulangzhejingyanItem;
import net.mcreator.ceshi.item.JianglidayinxiongjingyanItem;
import net.mcreator.ceshi.item.HuangjindezhexueItem;
import net.mcreator.ceshi.item.HqyanItem;
import net.mcreator.ceshi.item.HqshuiItem;
import net.mcreator.ceshi.item.HqleiItem;
import net.mcreator.ceshi.item.HqhuoItem;
import net.mcreator.ceshi.item.HqfengItem;
import net.mcreator.ceshi.item.HqcaoItem;
import net.mcreator.ceshi.item.HqbingItem;
import net.mcreator.ceshi.item.HhaokandelajiItem;
import net.mcreator.ceshi.item.GzsmzItem;
import net.mcreator.ceshi.item.GuzhonglingjianItem;
import net.mcreator.ceshi.item.GongzhuxinghuaItem;
import net.mcreator.ceshi.item.GongsideguguzhongItem;
import net.mcreator.ceshi.item.FulinjiaoItem;
import net.mcreator.ceshi.item.FfanrongdezhexueItem;
import net.mcreator.ceshi.item.FenliejinbiItem;
import net.mcreator.ceshi.item.FengdandaibiaoItem;
import net.mcreator.ceshi.item.FeiqiupingzhengItem;
import net.mcreator.ceshi.item.DjzstItem;
import net.mcreator.ceshi.item.DjzssjItem;
import net.mcreator.ceshi.item.DjzsshjsjItem;
import net.mcreator.ceshi.item.DjttItem;
import net.mcreator.ceshi.item.DjtsjItem;
import net.mcreator.ceshi.item.DjtjItem;
import net.mcreator.ceshi.item.DjqItem;
import net.mcreator.ceshi.item.DjhjtItem;
import net.mcreator.ceshi.item.DjhjsjItem;
import net.mcreator.ceshi.item.DjhjjItem;
import net.mcreator.ceshi.item.DjgItem;
import net.mcreator.ceshi.item.DjfItem;
import net.mcreator.ceshi.item.DjcItem;
import net.mcreator.ceshi.item.DisuiItem;
import net.mcreator.ceshi.item.DijingsuixieItem;
import net.mcreator.ceshi.item.DijingkuaiItem;
import net.mcreator.ceshi.item.DijingduanpianItem;
import net.mcreator.ceshi.item.DiijingqingjingItem;
import net.mcreator.ceshi.item.DdjzsjItem;
import net.mcreator.ceshi.item.DayingxiongdejingyanItem;
import net.mcreator.ceshi.item.CunqupingzhengItem;
import net.mcreator.ceshi.item.CukuangmanyueItem;
import net.mcreator.ceshi.item.CukuangkongyueItem;
import net.mcreator.ceshi.item.CukuangchiyueItem;
import net.mcreator.ceshi.item.ChunmeizhipaoItem;
import net.mcreator.ceshi.item.ChuangshijiejingItem;
import net.mcreator.ceshi.item.CeshiyongwupinItem;
import net.mcreator.ceshi.item.CebuzhunxiaItem;
import net.mcreator.ceshi.item.CchonggaodaodedezanxuItem;
import net.mcreator.ceshi.item.Ccangruimilinjian014Item;
import net.mcreator.ceshi.item.CaoyuanheItem;
import net.mcreator.ceshi.item.BushizidanheItem;
import net.mcreator.ceshi.item.BufengpingItem;
import net.mcreator.ceshi.item.Bbuzainianqingdeqincezhuang012Item;
import net.mcreator.ceshi.item.AxzstItem;
import net.mcreator.ceshi.item.AxzssjItem;
import net.mcreator.ceshi.item.AxzsshjsjItem;
import net.mcreator.ceshi.item.AxzsjItem;
import net.mcreator.ceshi.item.AxttItem;
import net.mcreator.ceshi.item.AxtsjItem;
import net.mcreator.ceshi.item.AxtjItem;
import net.mcreator.ceshi.item.AxqItem;
import net.mcreator.ceshi.item.AxhjtItem;
import net.mcreator.ceshi.item.AxhjsjItem;
import net.mcreator.ceshi.item.AxhjjItem;
import net.mcreator.ceshi.item.AxgItem;
import net.mcreator.ceshi.item.AxfItem;
import net.mcreator.ceshi.item.AxcItem;
import net.mcreator.ceshi.item.AixubingyusuixieItem;
import net.mcreator.ceshi.item.AixubingyukuaiItem;
import net.mcreator.ceshi.item.AixubingyuItem;
import net.mcreator.ceshi.item.AaixubingyuduanpianItem;
import net.mcreator.ceshi.PrimogemcraftMod;

@Mod.EventBusSubscriber(bus = Mod.EventBusSubscriber.Bus.MOD, value = Dist.CLIENT)
public class PrimogemcraftModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, PrimogemcraftMod.MODID);
	public static final RegistryObject<Item> MINGWEI_YIQIEDEKAISHI = REGISTRY.register("mingwei_yiqiedekaishi", () -> new BushizidanheItem());
	public static final RegistryObject<Item> YUANSHIKUANGSHI = block(PrimogemcraftModBlocks.YUANSHIKUANGSHI);
	public static final RegistryObject<Item> YUANSHI = REGISTRY.register("yuanshi", () -> new YuanshiItem());
	public static final RegistryObject<Item> XIXIANGYUZHIYUAN = REGISTRY.register("xixiangyuzhiyuan", () -> new XixiangyuzhiyuanItem());
	public static final RegistryObject<Item> JIJIUCHANZHIYUAN = REGISTRY.register("jijiuchanzhiyuan", () -> new JijiuchanzhiyuanItem());
	public static final RegistryObject<Item> YISHIJIEYUANMUMUBAN = block(PrimogemcraftModBlocks.YISHIJIEYUANMUMUBAN);
	public static final RegistryObject<Item> CHUANGSHIJIEJING = REGISTRY.register("chuangshijiejing", () -> new ChuangshijiejingItem());
	public static final RegistryObject<Item> YISHIJIEMUGUN = REGISTRY.register("yishijiemugun", () -> new YishijiemugunItem());
	public static final RegistryObject<Item> JIUCHANZHIYUANGAO = REGISTRY.register("jiuchanzhiyuangao", () -> new JiuchanzhiyuangaoItem());
	public static final RegistryObject<Item> WUQIEZHIHUIGUANG = REGISTRY.register("wuqiezhihuiguang", () -> new WuqiezhihuiguangItem());
	public static final RegistryObject<Item> JIUCHANZHIYUANKUAI = block(PrimogemcraftModBlocks.JIUCHANZHIYUANKUAI);
	public static final RegistryObject<Item> JIUCHANZHIYUANXIAN = REGISTRY.register("jiuchanzhiyuanxian", () -> new JiuchanzhiyuanxianItem());
	public static final RegistryObject<Item> YIYINHEDALETOU = REGISTRY.register("yiyinhedaletou", () -> new YiyinhedaletouItem());
	public static final RegistryObject<Item> MMOLA_01 = REGISTRY.register("mmola_01", () -> new Mmola01Item());
	public static final RegistryObject<Item> QQIYUAN_JIN_GUANG_SPAWN_EGG = REGISTRY.register("qqiyuan_jin_guang_spawn_egg", () -> new ForgeSpawnEggItem(PrimogemcraftModEntities.QQIYUAN_JIN_GUANG, -1536, -2191, new Item.Properties()));
	public static final RegistryObject<Item> Q_QYUANCHUZI_01_SPAWN_EGG = REGISTRY.register("q_qyuanchuzi_01_spawn_egg", () -> new ForgeSpawnEggItem(PrimogemcraftModEntities.Q_QYUANCHUZI_01, -3056653, -4118017, new Item.Properties()));
	public static final RegistryObject<Item> QQ_QYUANCHULAN_01_SPAWN_EGG = REGISTRY.register("qq_qyuanchulan_01_spawn_egg", () -> new ForgeSpawnEggItem(PrimogemcraftModEntities.QQ_QYUANCHULAN_01, -10254081, -5449985, new Item.Properties()));
	public static final RegistryObject<Item> JINGUANGBAODI_01 = REGISTRY.register("jinguangbaodi_01", () -> new Jinguangbaodi01Item());
	public static final RegistryObject<Item> XIWANGDEYITIAN_011 = REGISTRY.register("xiwangdeyitian_011", () -> new Xiwangdeyitian011Item());
	public static final RegistryObject<Item> BBUZAINIANQINGDEQINCEZHUANG_012 = REGISTRY.register("bbuzainianqingdeqincezhuang_012", () -> new Bbuzainianqingdeqincezhuang012Item());
	public static final RegistryObject<Item> SSHENHUDEZHUFU_013 = REGISTRY.register("sshenhudezhufu_013", () -> new Sshenhudezhufu013Item());
	public static final RegistryObject<Item> CCANGRUIMILINJIAN_014 = REGISTRY.register("ccangruimilinjian_014", () -> new Ccangruimilinjian014Item());
	public static final RegistryObject<Item> MOLADUI_02 = block(PrimogemcraftModBlocks.MOLADUI_02);
	public static final RegistryObject<Item> MOLAKUAI_01 = block(PrimogemcraftModBlocks.MOLAKUAI_01);
	public static final RegistryObject<Item> YIYISHIJIEMUBANLOUQI = block(PrimogemcraftModBlocks.YIYISHIJIEMUBANLOUQI);
	public static final RegistryObject<Item> YIYISHIJIEYUANMUBANZHUAN = block(PrimogemcraftModBlocks.YIYISHIJIEYUANMUBANZHUAN);
	public static final RegistryObject<Item> YIYISHIJIEMUZHALAN = block(PrimogemcraftModBlocks.YIYISHIJIEMUZHALAN);
	public static final RegistryObject<Item> YISHIJIEMUZHALAN = block(PrimogemcraftModBlocks.YISHIJIEMUZHALAN);
	public static final RegistryObject<Item> QINLAODEZHEXUE = REGISTRY.register("qinlaodezhexue", () -> new QinlaodezhexueItem());
	public static final RegistryObject<Item> HUANGJINDEZHEXUE = REGISTRY.register("huangjindezhexue", () -> new HuangjindezhexueItem());
	public static final RegistryObject<Item> FFANRONGDEZHEXUE = REGISTRY.register("ffanrongdezhexue", () -> new FfanrongdezhexueItem());
	public static final RegistryObject<Item> SANYUEQIDIAOXIANG_01 = block(PrimogemcraftModBlocks.SANYUEQIDIAOXIANG_01);
	public static final RegistryObject<Item> XIANGDANGANLAO = REGISTRY.register("xiangdanganlao", () -> new XiangdanganlaoItem());
	public static final RegistryObject<Item> TAIKONGMANBUCHANGPIAN = REGISTRY.register("taikongmanbuchangpian", () -> new TaikongmanbuchangpianItem());
	public static final RegistryObject<Item> YYANZIYUELIANGCHANGPIAN = REGISTRY.register("yyanziyueliangchangpian", () -> new YyanziyueliangchangpianItem());
	public static final RegistryObject<Item> JINGZHIMOLAKUAI = block(PrimogemcraftModBlocks.JINGZHIMOLAKUAI);
	public static final RegistryObject<Item> LLIANJIAMOLAKUAI = block(PrimogemcraftModBlocks.LLIANJIAMOLAKUAI);
	public static final RegistryObject<Item> LIANJIAMOLAKUAIBANKUAI = block(PrimogemcraftModBlocks.LIANJIAMOLAKUAIBANKUAI);
	public static final RegistryObject<Item> LLIANJIAMOLAKUIAITAIJIE = block(PrimogemcraftModBlocks.LLIANJIAMOLAKUIAITAIJIE);
	public static final RegistryObject<Item> LLIANJIAMOLAKUAIQIANG = block(PrimogemcraftModBlocks.LLIANJIAMOLAKUAIQIANG);
	public static final RegistryObject<Item> QIWUCHONGWANG = REGISTRY.register("qiwuchongwang", () -> new QiwuchongwangItem());
	public static final RegistryObject<Item> SSANBAMIANTOU = REGISTRY.register("ssanbamiantou", () -> new SsanbamiantouItem());
	public static final RegistryObject<Item> QQIWUZHANLIPINSHITI_SPAWN_EGG = REGISTRY.register("qqiwuzhanlipinshiti_spawn_egg", () -> new ForgeSpawnEggItem(PrimogemcraftModEntities.QQIWUZHANLIPINSHITI, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> KKUIJIACESHI_HELMET = REGISTRY.register("kkuijiaceshi_helmet", () -> new KkuijiaceshiItem.Helmet());
	public static final RegistryObject<Item> KKUIJIACESHI_CHESTPLATE = REGISTRY.register("kkuijiaceshi_chestplate", () -> new KkuijiaceshiItem.Chestplate());
	public static final RegistryObject<Item> KKUIJIACESHI_LEGGINGS = REGISTRY.register("kkuijiaceshi_leggings", () -> new KkuijiaceshiItem.Leggings());
	public static final RegistryObject<Item> KKUIJIACESHI_BOOTS = REGISTRY.register("kkuijiaceshi_boots", () -> new KkuijiaceshiItem.Boots());
	public static final RegistryObject<Item> MMOLAGAO = REGISTRY.register("mmolagao", () -> new MmolagaoItem());
	public static final RegistryObject<Item> MMOLAFU = REGISTRY.register("mmolafu", () -> new MmolafuItem());
	public static final RegistryObject<Item> MMOLACHAN = REGISTRY.register("mmolachan", () -> new MmolachanItem());
	public static final RegistryObject<Item> MMOLAJIAN = REGISTRY.register("mmolajian", () -> new MmolajianItem());
	public static final RegistryObject<Item> TASHANGLVTUCHANGPIAN = REGISTRY.register("tashanglvtuchangpian", () -> new TashanglvtuchangpianItem());
	public static final RegistryObject<Item> XIAOGUANZI = block(PrimogemcraftModBlocks.XIAOGUANZI);
	public static final RegistryObject<Item> DAGUANZI = block(PrimogemcraftModBlocks.DAGUANZI);
	public static final RegistryObject<Item> JINZHIMOLA = REGISTRY.register("jinzhimola", () -> new JinzhimolaItem());
	public static final RegistryObject<Item> WMOLADAI = REGISTRY.register("wmoladai", () -> new WmoladaiItem());
	public static final RegistryObject<Item> MMOLAPEIZIWUPIN = REGISTRY.register("mmolapeiziwupin", () -> new MmolapeiziwupinItem());
	public static final RegistryObject<Item> XIAODAIMOLA = REGISTRY.register("xiaodaimola", () -> new XiaodaimolaItem());
	public static final RegistryObject<Item> SHILIANCHOU = REGISTRY.register("shilianchou", () -> new ShilianchouItem());
	public static final RegistryObject<Item> BAIGUANGGUODUSHENGWU_SPAWN_EGG = REGISTRY.register("baiguangguodushengwu_spawn_egg", () -> new ForgeSpawnEggItem(PrimogemcraftModEntities.BAIGUANGGUODUSHENGWU, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> WAWANXIANGWUCHANGTOU = REGISTRY.register("wawanxiangwuchangtou", () -> new WawanxiangwuchangtouItem());
	public static final RegistryObject<Item> CEBUZHUNXIA = REGISTRY.register("cebuzhunxia", () -> new CebuzhunxiaItem());
	public static final RegistryObject<Item> XIANTIAOQIANG = REGISTRY.register("xiantiaoqiang", () -> new XiantiaoqiangItem());
	public static final RegistryObject<Item> WUFENGJIAN = REGISTRY.register("wufengjian", () -> new WufengjianItem());
	public static final RegistryObject<Item> GONGSIDEGUGUZHONG = REGISTRY.register("gongsideguguzhong", () -> new GongsideguguzhongItem());
	public static final RegistryObject<Item> FULINJIAO = REGISTRY.register("fulinjiao", () -> new FulinjiaoItem());
	public static final RegistryObject<Item> LAJITONG = block(PrimogemcraftModBlocks.LAJITONG);
	public static final RegistryObject<Item> LAJI = REGISTRY.register("laji", () -> new LajiItem());
	public static final RegistryObject<Item> LAJITONGZUNYAN = REGISTRY.register("lajitongzunyan", () -> new LajitongzunyanItem());
	public static final RegistryObject<Item> ZHUANGMANLAJIDELAJITONG = REGISTRY.register("zhuangmanlajidelajitong", () -> new ZhuangmanlajidelajitongItem());
	public static final RegistryObject<Item> ZHONGKOUWEITIEDING = REGISTRY.register("zhongkouweitieding", () -> new ZhongkouweitiedingItem());
	public static final RegistryObject<Item> HHAOKANDELAJI = REGISTRY.register("hhaokandelaji", () -> new HhaokandelajiItem());
	public static final RegistryObject<Item> CESHIYONGWUPIN = REGISTRY.register("ceshiyongwupin", () -> new CeshiyongwupinItem());
	public static final RegistryObject<Item> GANJINGLAJITONGXIANGZI = block(PrimogemcraftModBlocks.GANJINGLAJITONGXIANGZI);
	public static final RegistryObject<Item> MMOLAZHILAJITONG = block(PrimogemcraftModBlocks.MMOLAZHILAJITONG);
	public static final RegistryObject<Item> ZHZHENYINHEDALETOU = REGISTRY.register("zhzhenyinhedaletou", () -> new ZhzhenyinhedaletouItem());
	public static final RegistryObject<Item> ZIYOUSONGSHIKUANGSHI = block(PrimogemcraftModBlocks.ZIYOUSONGSHIKUANGSHI);
	public static final RegistryObject<Item> ZIZIYOUSONGSHISUIXIE = REGISTRY.register("ziziyousongshisuixie", () -> new ZiziyousongshisuixieItem());
	public static final RegistryObject<Item> ZZIYOUSONGSHIDUANPIAN = REGISTRY.register("zziyousongshiduanpian", () -> new ZziyousongshiduanpianItem());
	public static final RegistryObject<Item> ZZIYOUSONGSHIKUAI = REGISTRY.register("zziyousongshikuai", () -> new ZziyousongshikuaiItem());
	public static final RegistryObject<Item> ZZIYOUSONGSHI = REGISTRY.register("zziyousongshi", () -> new ZziyousongshiItem());
	public static final RegistryObject<Item> ZIYOUSONGSHIKUAI = block(PrimogemcraftModBlocks.ZIYOUSONGSHIKUAI);
	public static final RegistryObject<Item> BUFENGPING = REGISTRY.register("bufengping", () -> new BufengpingItem());
	public static final RegistryObject<Item> JIANLAOKUANGSHI = block(PrimogemcraftModBlocks.JIANLAOKUANGSHI);
	public static final RegistryObject<Item> JIANRANSUIXIE = REGISTRY.register("jianransuixie", () -> new JianransuixieItem());
	public static final RegistryObject<Item> JIANLAODUANPIAN = REGISTRY.register("jianlaoduanpian", () -> new JianlaoduanpianItem());
	public static final RegistryObject<Item> JIANLAOHUANGYU = REGISTRY.register("jianlaohuangyu", () -> new JianlaohuangyuItem());
	public static final RegistryObject<Item> JIANLAOHUANGYUKUAI = block(PrimogemcraftModBlocks.JIANLAOHUANGYUKUAI);
	public static final RegistryObject<Item> ZUISHENGSUIXIE = REGISTRY.register("zuishengsuixie", () -> new ZuishengsuixieItem());
	public static final RegistryObject<Item> ZUISHENGDUANPIAN = REGISTRY.register("zuishengduanpian", () -> new ZuishengduanpianItem());
	public static final RegistryObject<Item> ZUISHENGKUAI = REGISTRY.register("zuishengkuai", () -> new ZuishengkuaiItem());
	public static final RegistryObject<Item> ZUISHENGZIJING = REGISTRY.register("zuishengzijing", () -> new ZuishengzijingItem());
	public static final RegistryObject<Item> ZUISHENGKUANGSHI = block(PrimogemcraftModBlocks.ZUISHENGKUANGSHI);
	public static final RegistryObject<Item> ZUISNEGZIJINGKUAI = block(PrimogemcraftModBlocks.ZUISNEGZIJINGKUAI);
	public static final RegistryObject<Item> MENGYING = REGISTRY.register("mengying", () -> new MengyingItem());
	public static final RegistryObject<Item> POSUIMENGYING = REGISTRY.register("posuimengying", () -> new PosuimengyingItem());
	public static final RegistryObject<Item> SHENGZHANGKUANGSHI = block(PrimogemcraftModBlocks.SHENGZHANGKUANGSHI);
	public static final RegistryObject<Item> SHENGZHANGBIFEISUIXIE = REGISTRY.register("shengzhangbifeisuixie", () -> new ShengzhangbifeisuixieItem());
	public static final RegistryObject<Item> SHENGZHANGDUANPIAN = REGISTRY.register("shengzhangduanpian", () -> new ShengzhangduanpianItem());
	public static final RegistryObject<Item> SHENGZHANGKUAI = REGISTRY.register("shengzhangkuai", () -> new ShengzhangkuaiItem());
	public static final RegistryObject<Item> SHENGZHANGBIFEI = REGISTRY.register("shengzhangbifei", () -> new ShengzhangbifeiItem());
	public static final RegistryObject<Item> SHENGZHANGBIFEIDAKUAI = block(PrimogemcraftModBlocks.SHENGZHANGBIFEIDAKUAI);
	public static final RegistryObject<Item> CAOYUANHESHENGWU_SPAWN_EGG = REGISTRY.register("caoyuanheshengwu_spawn_egg", () -> new ForgeSpawnEggItem(PrimogemcraftModEntities.CAOYUANHESHENGWU, -13369600, -3342490, new Item.Properties()));
	public static final RegistryObject<Item> CAOYUANHE = REGISTRY.register("caoyuanhe", () -> new CaoyuanheItem());
	public static final RegistryObject<Item> CAOYUANHEKUAI = block(PrimogemcraftModBlocks.CAOYUANHEKUAI);
	public static final RegistryObject<Item> CAOYUANHEHUAMUBAN = block(PrimogemcraftModBlocks.CAOYUANHEHUAMUBAN);
	public static final RegistryObject<Item> CAOYUANHEHUABUBAN_2 = block(PrimogemcraftModBlocks.CAOYUANHEHUABUBAN_2);
	public static final RegistryObject<Item> CCAOYUANHEHUAMUBAN_3 = block(PrimogemcraftModBlocks.CCAOYUANHEHUAMUBAN_3);
	public static final RegistryObject<Item> CESHI_MUCAIBAO_STAIRS = block(PrimogemcraftModBlocks.CESHI_MUCAIBAO_STAIRS);
	public static final RegistryObject<Item> CESHI_MUCAIBAO_SLAB = block(PrimogemcraftModBlocks.CESHI_MUCAIBAO_SLAB);
	public static final RegistryObject<Item> CESHI_MUCAIBAO_FENCE = block(PrimogemcraftModBlocks.CESHI_MUCAIBAO_FENCE);
	public static final RegistryObject<Item> CESHI_MUCAIBAO_FENCE_GATE = block(PrimogemcraftModBlocks.CESHI_MUCAIBAO_FENCE_GATE);
	public static final RegistryObject<Item> CESHI_MUCAIBAO_PRESSURE_PLATE = block(PrimogemcraftModBlocks.CESHI_MUCAIBAO_PRESSURE_PLATE);
	public static final RegistryObject<Item> CESHI_MUCAIBAO_BUTTON = block(PrimogemcraftModBlocks.CESHI_MUCAIBAO_BUTTON);
	public static final RegistryObject<Item> CAOMULOUTI_21 = block(PrimogemcraftModBlocks.CAOMULOUTI_21);
	public static final RegistryObject<Item> CAOMU_22 = block(PrimogemcraftModBlocks.CAOMU_22);
	public static final RegistryObject<Item> CAOMO_23 = block(PrimogemcraftModBlocks.CAOMO_23);
	public static final RegistryObject<Item> CAOMU_24 = block(PrimogemcraftModBlocks.CAOMU_24);
	public static final RegistryObject<Item> CAOMU_25 = block(PrimogemcraftModBlocks.CAOMU_25);
	public static final RegistryObject<Item> CAOMU_26 = block(PrimogemcraftModBlocks.CAOMU_26);
	public static final RegistryObject<Item> CAOMU_31 = block(PrimogemcraftModBlocks.CAOMU_31);
	public static final RegistryObject<Item> CAOMU_32 = block(PrimogemcraftModBlocks.CAOMU_32);
	public static final RegistryObject<Item> CAOMU_33 = block(PrimogemcraftModBlocks.CAOMU_33);
	public static final RegistryObject<Item> CAOMU_34 = block(PrimogemcraftModBlocks.CAOMU_34);
	public static final RegistryObject<Item> CAOMU_35 = block(PrimogemcraftModBlocks.CAOMU_35);
	public static final RegistryObject<Item> CAOMU_36 = block(PrimogemcraftModBlocks.CAOMU_36);
	public static final RegistryObject<Item> PENGKELUODEJINGSHEN = REGISTRY.register("pengkeluodejingshen", () -> new PengkeluodejingshenItem());
	public static final RegistryObject<Item> DIJINGQINJINGKUANGSHI = block(PrimogemcraftModBlocks.DIJINGQINJINGKUANGSHI);
	public static final RegistryObject<Item> DIJINGSUIXIE = REGISTRY.register("dijingsuixie", () -> new DijingsuixieItem());
	public static final RegistryObject<Item> DIJINGDUANPIAN = REGISTRY.register("dijingduanpian", () -> new DijingduanpianItem());
	public static final RegistryObject<Item> DIJINGKUAI = REGISTRY.register("dijingkuai", () -> new DijingkuaiItem());
	public static final RegistryObject<Item> DIIJINGQINGJING = REGISTRY.register("diijingqingjing", () -> new DiijingqingjingItem());
	public static final RegistryObject<Item> DIJINGQINGJINKUAI = block(PrimogemcraftModBlocks.DIJINGQINGJINKUAI);
	public static final RegistryObject<Item> LIANJIAXIAJIEHEJINKUAI = block(PrimogemcraftModBlocks.LIANJIAXIAJIEHEJINKUAI);
	public static final RegistryObject<Item> ZHAPIANDINGZHENGSHI = REGISTRY.register("zhapiandingzhengshi", () -> new ZhapiandingzhengshiItem());
	public static final RegistryObject<Item> RANYUANMANAOKUANGSHI = block(PrimogemcraftModBlocks.RANYUANMANAOKUANGSHI);
	public static final RegistryObject<Item> RANYUANSUIXIE = REGISTRY.register("ranyuansuixie", () -> new RanyuansuixieItem());
	public static final RegistryObject<Item> RANYUANDUANPIAN = REGISTRY.register("ranyuanduanpian", () -> new RanyuanduanpianItem());
	public static final RegistryObject<Item> RANYUANKUAI = REGISTRY.register("ranyuankuai", () -> new RanyuankuaiItem());
	public static final RegistryObject<Item> RRANYUANMANAO = REGISTRY.register("rranyuanmanao", () -> new RranyuanmanaoItem());
	public static final RegistryObject<Item> RANYUANKUAI_2 = block(PrimogemcraftModBlocks.RANYUANKUAI_2);
	public static final RegistryObject<Item> MUTANKUAI = block(PrimogemcraftModBlocks.MUTANKUAI);
	public static final RegistryObject<Item> XIJAIEYANGENGDI = block(PrimogemcraftModBlocks.XIJAIEYANGENGDI);
	public static final RegistryObject<Item> AIXUBINGYUKUANGSHI = block(PrimogemcraftModBlocks.AIXUBINGYUKUANGSHI);
	public static final RegistryObject<Item> AIXUBINGYUSUIXIE = REGISTRY.register("aixubingyusuixie", () -> new AixubingyusuixieItem());
	public static final RegistryObject<Item> AAIXUBINGYUDUANPIAN = REGISTRY.register("aaixubingyuduanpian", () -> new AaixubingyuduanpianItem());
	public static final RegistryObject<Item> AIXUBINGYUKUAI = REGISTRY.register("aixubingyukuai", () -> new AixubingyukuaiItem());
	public static final RegistryObject<Item> AIXUBINGYU = REGISTRY.register("aixubingyu", () -> new AixubingyuItem());
	public static final RegistryObject<Item> AIXUBINGYUFANGKU_I = block(PrimogemcraftModBlocks.AIXUBINGYUFANGKU_I);
	public static final RegistryObject<Item> YUANSUJINGTI = REGISTRY.register("yuansujingti", () -> new YuansujingtiItem());
	public static final RegistryObject<Item> YUANSUJINGSHIKUAI = block(PrimogemcraftModBlocks.YUANSUJINGSHIKUAI);
	public static final RegistryObject<Item> SHANBIANZHICHEN = REGISTRY.register("shanbianzhichen", () -> new ShanbianzhichenItem());
	public static final RegistryObject<Item> XIAODENG_SPAWN_EGG = REGISTRY.register("xiaodeng_spawn_egg", () -> new ForgeSpawnEggItem(PrimogemcraftModEntities.XIAODENG, -13312, -26368, new Item.Properties()));
	public static final RegistryObject<Item> XIAODENGWUPIN = REGISTRY.register("xiaodengwupin", () -> new XiaodengwupinItem());
	public static final RegistryObject<Item> WEIZHIYEPIAN = REGISTRY.register("weizhiyepian", () -> new WeizhiyepianItem());
	public static final RegistryObject<Item> CESHIXIAODENGFASHEQI = block(PrimogemcraftModBlocks.CESHIXIAODENGFASHEQI);
	public static final RegistryObject<Item> CHIYUEJINSHU = REGISTRY.register("chiyuejinshu", () -> new KongyuejinshuItem());
	public static final RegistryObject<Item> XINYUEJINSHU = REGISTRY.register("xinyuejinshu", () -> new XinyuejinshuItem());
	public static final RegistryObject<Item> MANYUEJINSHU = REGISTRY.register("manyuejinshu", () -> new ManyuejinshuItem());
	public static final RegistryObject<Item> KONGYUEZHUFU = REGISTRY.register("kongyuezhufu", () -> new KongyuezhufuItem());
	public static final RegistryObject<Item> XINYUEKUANGSHI = block(PrimogemcraftModBlocks.XINYUEKUANGSHI);
	public static final RegistryObject<Item> MANYUEJINSHUKUANGSHI = block(PrimogemcraftModBlocks.MANYUEJINSHUKUANGSHI);
	public static final RegistryObject<Item> CHIYUEJINSHUKUANG = block(PrimogemcraftModBlocks.CHIYUEJINSHUKUANG);
	public static final RegistryObject<Item> SANYUEZHUFU = REGISTRY.register("sanyuezhufu", () -> new SanyuezhufuItem());
	public static final RegistryObject<Item> LUANQIBAZAODEDAIMA = REGISTRY.register("luanqibazaodedaima", () -> new LuanqibazaodedaimaItem());
	public static final RegistryObject<Item> YOUDIANQIQIAODEDAIMA = REGISTRY.register("youdianqiqiaodedaima", () -> new YoudianqiqiaodedaimaItem());
	public static final RegistryObject<Item> ZHONGGUIZHONGJUDEDAIMA = REGISTRY.register("zhongguizhongjudedaima", () -> new ZhongguizhongjudedaimaItem());
	public static final RegistryObject<Item> JINGQUEYOUYADAIMA = REGISTRY.register("jingqueyouyadaima", () -> new JingqueyouyadaimaItem());
	public static final RegistryObject<Item> MEIYOUZHUSHIDAIMA = REGISTRY.register("meiyouzhushidaima", () -> new MeiyouzhushidaimaItem());
	public static final RegistryObject<Item> WUXIANDIGUIDEDAIMA = REGISTRY.register("wuxiandiguidedaima", () -> new WuxiandiguidedaimaItem());
	public static final RegistryObject<Item> FENLIEJINBI = REGISTRY.register("fenliejinbi", () -> new FenliejinbiItem());
	public static final RegistryObject<Item> YUZHOUSUIPIAN = REGISTRY.register("yuzhousuipian", () -> new YuzhousuipianItem());
	public static final RegistryObject<Item> SUIJI_1SHIJIAN = REGISTRY.register("suiji_1shijian", () -> new Suiji1shijianItem());
	public static final RegistryObject<Item> CHUANGZAOXIAODENGFASHEQI = block(PrimogemcraftModBlocks.CHUANGZAOXIAODENGFASHEQI);
	public static final RegistryObject<Item> CCHONGGAODAODEDEZANXU = REGISTRY.register("cchonggaodaodedezanxu", () -> new CchonggaodaodedezanxuItem());
	public static final RegistryObject<Item> LIULANGZHEDEJINGYAN = REGISTRY.register("liulangzhedejingyan", () -> new LiulangzhedejingyanItem());
	public static final RegistryObject<Item> MAOXIANJIADEJINGYAN = REGISTRY.register("maoxianjiadejingyan", () -> new MaoxianjiadejingyanItem());
	public static final RegistryObject<Item> DAYINGXIONGDEJINGYAN = REGISTRY.register("dayingxiongdejingyan", () -> new DayingxiongdejingyanItem());
	public static final RegistryObject<Item> YISHIJIEMUBAN_PLANKS = block(PrimogemcraftModBlocks.YISHIJIEMUBAN_PLANKS);
	public static final RegistryObject<Item> YISHIJIEMUBAN_STAIRS = block(PrimogemcraftModBlocks.YISHIJIEMUBAN_STAIRS);
	public static final RegistryObject<Item> YISHIJIEMUBAN_SLAB = block(PrimogemcraftModBlocks.YISHIJIEMUBAN_SLAB);
	public static final RegistryObject<Item> YISHIJIEMUBAN_FENCE = block(PrimogemcraftModBlocks.YISHIJIEMUBAN_FENCE);
	public static final RegistryObject<Item> YISHIJIEMUBAN_FENCE_GATE = block(PrimogemcraftModBlocks.YISHIJIEMUBAN_FENCE_GATE);
	public static final RegistryObject<Item> YISHIJIEMUBAN_PRESSURE_PLATE = block(PrimogemcraftModBlocks.YISHIJIEMUBAN_PRESSURE_PLATE);
	public static final RegistryObject<Item> YISHIJIEMUBAN_BUTTON = block(PrimogemcraftModBlocks.YISHIJIEMUBAN_BUTTON);
	public static final RegistryObject<Item> D_11 = block(PrimogemcraftModBlocks.D_11);
	public static final RegistryObject<Item> D_12 = block(PrimogemcraftModBlocks.D_12);
	public static final RegistryObject<Item> D_13 = block(PrimogemcraftModBlocks.D_13);
	public static final RegistryObject<Item> D_14 = block(PrimogemcraftModBlocks.D_14);
	public static final RegistryObject<Item> D_15 = block(PrimogemcraftModBlocks.D_15);
	public static final RegistryObject<Item> D_16 = block(PrimogemcraftModBlocks.D_16);
	public static final RegistryObject<Item> D_17 = block(PrimogemcraftModBlocks.D_17);
	public static final RegistryObject<Item> JIANGLILIULANGZHEJINGYAN = REGISTRY.register("jiangliliulangzhejingyan", () -> new JiangliliulangzhejingyanItem());
	public static final RegistryObject<Item> JIANGLIMAOXIANJIAJINGYAN = REGISTRY.register("jianglimaoxianjiajingyan", () -> new JianglimaoxianjiajingyanItem());
	public static final RegistryObject<Item> JIANGLIDAYINXIONGJINGYAN = REGISTRY.register("jianglidayinxiongjingyan", () -> new JianglidayinxiongjingyanItem());
	public static final RegistryObject<Item> TIAOGUOZHANG = REGISTRY.register("tiaoguozhang", () -> new TiaoguozhangItem());
	public static final RegistryObject<Item> DISUIKUAI_1 = block(PrimogemcraftModBlocks.DISUIKUAI_1);
	public static final RegistryObject<Item> DISUISHUIJINGTI = block(PrimogemcraftModBlocks.DISUISHUIJINGTI);
	public static final RegistryObject<Item> DISUI = REGISTRY.register("disui", () -> new DisuiItem());
	public static final RegistryObject<Item> CANGSANGSHIZHUAN = block(PrimogemcraftModBlocks.CANGSANGSHIZHUAN);
	public static final RegistryObject<Item> XIUTIEKUAI = block(PrimogemcraftModBlocks.XIUTIEKUAI);
	public static final RegistryObject<Item> CSHIXIUTIEZHALAN = block(PrimogemcraftModBlocks.CSHIXIUTIEZHALAN);
	public static final RegistryObject<Item> XIUMU = block(PrimogemcraftModBlocks.XIUMU);
	public static final RegistryObject<Item> XIUXIUMULOUQI = block(PrimogemcraftModBlocks.XIUXIUMULOUQI);
	public static final RegistryObject<Item> XIUMUZHALAN = block(PrimogemcraftModBlocks.XIUMUZHALAN);
	public static final RegistryObject<Item> CANGSANGSHIZHUANLOUTI = block(PrimogemcraftModBlocks.CANGSANGSHIZHUANLOUTI);
	public static final RegistryObject<Item> CANGSANGSHIZHUANTAIJIE = block(PrimogemcraftModBlocks.CANGSANGSHIZHUANTAIJIE);
	public static final RegistryObject<Item> CANGSANGSHIZHUANWEIQIANG = block(PrimogemcraftModBlocks.CANGSANGSHIZHUANWEIQIANG);
	public static final RegistryObject<Item> YIYIMUGUOSHI = REGISTRY.register("yiyimuguoshi", () -> new YiyimuguoshiItem());
	public static final RegistryObject<Item> WANSHINANG = REGISTRY.register("wanshinang", () -> new WanshinangItem());
	public static final RegistryObject<Item> LAJITONGSUIPIAN = REGISTRY.register("lajitongsuipian", () -> new LajitongsuipianItem());
	public static final RegistryObject<Item> LIULANGZHEZHINANG = REGISTRY.register("liulangzhezhinang", () -> new LiulangzhezhinangItem());
	public static final RegistryObject<Item> MAOXIANJIAZHINANG = REGISTRY.register("maoxianjiazhinang", () -> new MaoxianjiazhinangItem());
	public static final RegistryObject<Item> YIBANGRENZHINANG = REGISTRY.register("yibangrenzhinang", () -> new ZhangquanzhezhinangItem());
	public static final RegistryObject<Item> YINGJICUNCHUNANG = REGISTRY.register("yingjicunchunang", () -> new YibangrenzhinangItem());
	public static final RegistryObject<Item> SHIZUOYUANSHIKUAI = block(PrimogemcraftModBlocks.SHIZUOYUANSHIKUAI);
	public static final RegistryObject<Item> FEIQIUPINGZHENG = REGISTRY.register("feiqiupingzheng", () -> new FeiqiupingzhengItem());
	public static final RegistryObject<Item> ZHAIQUAN = REGISTRY.register("zhaiquan", () -> new ZhaiquanItem());
	public static final RegistryObject<Item> TEZHIDIEYINGQI = REGISTRY.register("tezhidieyingqi", () -> new TezhidieyingqiItem());
	public static final RegistryObject<Item> WUQIE_2 = REGISTRY.register("wuqie_2", () -> new Wuqie2Item());
	public static final RegistryObject<Item> WUQIE_3 = REGISTRY.register("wuqie_3", () -> new Wuqie3Item());
	public static final RegistryObject<Item> WUQIE_4 = REGISTRY.register("wuqie_4", () -> new Wuqie4Item());
	public static final RegistryObject<Item> WUQIE_5 = REGISTRY.register("wuqie_5", () -> new Wuqie5Item());
	public static final RegistryObject<Item> LAOSHI = REGISTRY.register("laoshi", () -> new LaoshiItem());
	public static final RegistryObject<Item> KAIFAQIANGZHI_01 = REGISTRY.register("kaifaqiangzhi_01", () -> new Kaifaqiangzhi01Item());
	public static final RegistryObject<Item> XIAOHEITA_SPAWN_EGG = REGISTRY.register("xiaoheita_spawn_egg", () -> new ForgeSpawnEggItem(PrimogemcraftModEntities.XIAOHEITA, -7370515, -10414411, new Item.Properties()));
	public static final RegistryObject<Item> SHENSHENGHUABAN = REGISTRY.register("shenshenghuaban", () -> new ShenshenghuabanItem());
	public static final RegistryObject<Item> SHENBANYANYUANSHIKUANGSHI = block(PrimogemcraftModBlocks.SHENBANYANYUANSHIKUANGSHI);
	public static final RegistryObject<Item> SHENBANJIANLAOHUANGYUKUANGSHI = block(PrimogemcraftModBlocks.SHENBANJIANLAOHUANGYUKUANGSHI);
	public static final RegistryObject<Item> GONGZHUXINGHUA = REGISTRY.register("gongzhuxinghua", () -> new GongzhuxinghuaItem());
	public static final RegistryObject<Item> XINGHUI = REGISTRY.register("xinghui", () -> new XinghuiItem());
	public static final RegistryObject<Item> XINGCHEN = REGISTRY.register("xingchen", () -> new XingchenItem());
	public static final RegistryObject<Item> JIANMUSHENGFAQI = REGISTRY.register("jianmushengfaqi", () -> new JianmushengfaqiItem());
	public static final RegistryObject<Item> YUANSHIYUANPEI = REGISTRY.register("yuanshiyuanpei", () -> new YuanshiyuanpeiItem());
	public static final RegistryObject<Item> YUANSHIJIAN = REGISTRY.register("yuanshijian", () -> new YuanshijianItem());
	public static final RegistryObject<Item> YUANSHIGAO = REGISTRY.register("yuanshigao", () -> new YuanshigaoItem());
	public static final RegistryObject<Item> YUANSHIFU = REGISTRY.register("yuanshifu", () -> new YuanshifuItem());
	public static final RegistryObject<Item> YUANSHIQIAO = REGISTRY.register("yuanshiqiao", () -> new YuanshiqiaoItem());
	public static final RegistryObject<Item> YUANSHICHUTOU = REGISTRY.register("yuanshichutou", () -> new YuanshichutouItem());
	public static final RegistryObject<Item> SHENGJIZIZAITIE = REGISTRY.register("shengjizizaitie", () -> new ShengjizizaitieItem());
	public static final RegistryObject<Item> SHENGJIZIZAIZUAN = REGISTRY.register("shengjizizaizuan", () -> new ShengjizizaizuanItem());
	public static final RegistryObject<Item> SHENGJIZIZAIHEJ = REGISTRY.register("shengjizizaihej", () -> new ShengjizizaihejItem());
	public static final RegistryObject<Item> SHENGJIZUANSHEJIN = REGISTRY.register("shengjizuanshejin", () -> new ShengjizuanshejinItem());
	public static final RegistryObject<Item> ZIZAITIEJIAN = REGISTRY.register("zizaitiejian", () -> new ZizaitiejianItem());
	public static final RegistryObject<Item> ZIZAIZUANSHIJIAN = REGISTRY.register("zizaizuanshijian", () -> new ZizaizuanshijianItem());
	public static final RegistryObject<Item> ZIZAIHEJINJIAN = REGISTRY.register("zizaihejinjian", () -> new ZizaihejinjianItem());
	public static final RegistryObject<Item> ZIZGAO = REGISTRY.register("zizgao", () -> new ZizgaoItem());
	public static final RegistryObject<Item> ZIZAIFU = REGISTRY.register("zizaifu", () -> new ZizaifuItem());
	public static final RegistryObject<Item> JIANLAOKUAIWUPIN = REGISTRY.register("jianlaokuaiwupin", () -> new JianlaokuaiwupinItem());
	public static final RegistryObject<Item> ZIZAIQIAO = REGISTRY.register("zizaiqiao", () -> new ZizaiqiaoItem());
	public static final RegistryObject<Item> ZIZAICHU = REGISTRY.register("zizaichu", () -> new ZizaichuItem());
	public static final RegistryObject<Item> ZIZAITIEJIA_HELMET = REGISTRY.register("zizaitiejia_helmet", () -> new ZizaitiejiaItem.Helmet());
	public static final RegistryObject<Item> ZIZAITIEJIA_CHESTPLATE = REGISTRY.register("zizaitiejia_chestplate", () -> new ZizaitiejiaItem.Chestplate());
	public static final RegistryObject<Item> ZIZAITIEJIA_LEGGINGS = REGISTRY.register("zizaitiejia_leggings", () -> new ZizaitiejiaItem.Leggings());
	public static final RegistryObject<Item> ZIZAITIEJIA_BOOTS = REGISTRY.register("zizaitiejia_boots", () -> new ZizaitiejiaItem.Boots());
	public static final RegistryObject<Item> ZIZAIZUANTAO_HELMET = REGISTRY.register("zizaizuantao_helmet", () -> new ZizaizuantaoItem.Helmet());
	public static final RegistryObject<Item> ZIZAIZUANTAO_CHESTPLATE = REGISTRY.register("zizaizuantao_chestplate", () -> new ZizaizuantaoItem.Chestplate());
	public static final RegistryObject<Item> ZIZAIZUANTAO_LEGGINGS = REGISTRY.register("zizaizuantao_leggings", () -> new ZizaizuantaoItem.Leggings());
	public static final RegistryObject<Item> ZIZAIZUANTAO_BOOTS = REGISTRY.register("zizaizuantao_boots", () -> new ZizaizuantaoItem.Boots());
	public static final RegistryObject<Item> ZIZIZAIHEJINTAO_HELMET = REGISTRY.register("zizizaihejintao_helmet", () -> new ZizizaihejintaoItem.Helmet());
	public static final RegistryObject<Item> ZIZIZAIHEJINTAO_CHESTPLATE = REGISTRY.register("zizizaihejintao_chestplate", () -> new ZizizaihejintaoItem.Chestplate());
	public static final RegistryObject<Item> ZIZIZAIHEJINTAO_LEGGINGS = REGISTRY.register("zizizaihejintao_leggings", () -> new ZizizaihejintaoItem.Leggings());
	public static final RegistryObject<Item> ZIZIZAIHEJINTAO_BOOTS = REGISTRY.register("zizizaihejintao_boots", () -> new ZizizaihejintaoItem.Boots());
	public static final RegistryObject<Item> SHENGJIJLTIEWP = REGISTRY.register("shengjijltiewp", () -> new ShengjijltiewpItem());
	public static final RegistryObject<Item> SHENGJIJLZSWP = REGISTRY.register("shengjijlzswp", () -> new ShengjijlzswpItem());
	public static final RegistryObject<Item> SHENGJIJLHJWP = REGISTRY.register("shengjijlhjwp", () -> new ShengjijlhjwpItem());
	public static final RegistryObject<Item> SSHENGJIJLZSSHJWP = REGISTRY.register("sshengjijlzsshjwp", () -> new SshengjijlzsshjwpItem());
	public static final RegistryObject<Item> JLJTIE = REGISTRY.register("jljtie", () -> new JljtieItem());
	public static final RegistryObject<Item> JLJZS = REGISTRY.register("jljzs", () -> new JljzsItem());
	public static final RegistryObject<Item> JJLJXJHJ = REGISTRY.register("jjljxjhj", () -> new JjljxjhjItem());
	public static final RegistryObject<Item> JLG = REGISTRY.register("jlg", () -> new JlgItem());
	public static final RegistryObject<Item> JLF = REGISTRY.register("jlf", () -> new JlfItem());
	public static final RegistryObject<Item> JLQ = REGISTRY.register("jlq", () -> new JlqItem());
	public static final RegistryObject<Item> JLC = REGISTRY.register("jlc", () -> new JlcItem());
	public static final RegistryObject<Item> KJJLT_HELMET = REGISTRY.register("kjjlt_helmet", () -> new KjjltItem.Helmet());
	public static final RegistryObject<Item> KJJLT_CHESTPLATE = REGISTRY.register("kjjlt_chestplate", () -> new KjjltItem.Chestplate());
	public static final RegistryObject<Item> KJJLT_LEGGINGS = REGISTRY.register("kjjlt_leggings", () -> new KjjltItem.Leggings());
	public static final RegistryObject<Item> KJJLT_BOOTS = REGISTRY.register("kjjlt_boots", () -> new KjjltItem.Boots());
	public static final RegistryObject<Item> JLKJZS_HELMET = REGISTRY.register("jlkjzs_helmet", () -> new JlkjzsItem.Helmet());
	public static final RegistryObject<Item> JLKJZS_CHESTPLATE = REGISTRY.register("jlkjzs_chestplate", () -> new JlkjzsItem.Chestplate());
	public static final RegistryObject<Item> JLKJZS_LEGGINGS = REGISTRY.register("jlkjzs_leggings", () -> new JlkjzsItem.Leggings());
	public static final RegistryObject<Item> JLKJZS_BOOTS = REGISTRY.register("jlkjzs_boots", () -> new JlkjzsItem.Boots());
	public static final RegistryObject<Item> JLKJHJ_HELMET = REGISTRY.register("jlkjhj_helmet", () -> new JlkjhjItem.Helmet());
	public static final RegistryObject<Item> JLKJHJ_CHESTPLATE = REGISTRY.register("jlkjhj_chestplate", () -> new JlkjhjItem.Chestplate());
	public static final RegistryObject<Item> JLKJHJ_LEGGINGS = REGISTRY.register("jlkjhj_leggings", () -> new JlkjhjItem.Leggings());
	public static final RegistryObject<Item> JLKJHJ_BOOTS = REGISTRY.register("jlkjhj_boots", () -> new JlkjhjItem.Boots());
	public static final RegistryObject<Item> ZSTJ = REGISTRY.register("zstj", () -> new ZstjItem());
	public static final RegistryObject<Item> ZSZSJ = REGISTRY.register("zszsj", () -> new ZszsjItem());
	public static final RegistryObject<Item> ZSHJJ = REGISTRY.register("zshjj", () -> new ZshjjItem());
	public static final RegistryObject<Item> SJZST = REGISTRY.register("sjzst", () -> new SjzstItem());
	public static final RegistryObject<Item> SSJZSZS = REGISTRY.register("ssjzszs", () -> new SsjzszsItem());
	public static final RegistryObject<Item> SJZSHJ = REGISTRY.register("sjzshj", () -> new SjzshjItem());
	public static final RegistryObject<Item> SJZSZSSHJ = REGISTRY.register("sjzszsshj", () -> new SjzszsshjItem());
	public static final RegistryObject<Item> ZSG = REGISTRY.register("zsg", () -> new ZsgItem());
	public static final RegistryObject<Item> ZSQ = REGISTRY.register("zsq", () -> new ZsqItem());
	public static final RegistryObject<Item> ZSF = REGISTRY.register("zsf", () -> new ZsfItem());
	public static final RegistryObject<Item> ZSC = REGISTRY.register("zsc", () -> new ZscItem());
	public static final RegistryObject<Item> ZSTKJ_HELMET = REGISTRY.register("zstkj_helmet", () -> new ZstkjItem.Helmet());
	public static final RegistryObject<Item> ZSTKJ_CHESTPLATE = REGISTRY.register("zstkj_chestplate", () -> new ZstkjItem.Chestplate());
	public static final RegistryObject<Item> ZSTKJ_LEGGINGS = REGISTRY.register("zstkj_leggings", () -> new ZstkjItem.Leggings());
	public static final RegistryObject<Item> ZSTKJ_BOOTS = REGISTRY.register("zstkj_boots", () -> new ZstkjItem.Boots());
	public static final RegistryObject<Item> ZSZST_HELMET = REGISTRY.register("zszst_helmet", () -> new ZszstItem.Helmet());
	public static final RegistryObject<Item> ZSZST_CHESTPLATE = REGISTRY.register("zszst_chestplate", () -> new ZszstItem.Chestplate());
	public static final RegistryObject<Item> ZSZST_LEGGINGS = REGISTRY.register("zszst_leggings", () -> new ZszstItem.Leggings());
	public static final RegistryObject<Item> ZSZST_BOOTS = REGISTRY.register("zszst_boots", () -> new ZszstItem.Boots());
	public static final RegistryObject<Item> ZSHJT_HELMET = REGISTRY.register("zshjt_helmet", () -> new ZshjtItem.Helmet());
	public static final RegistryObject<Item> ZSHJT_CHESTPLATE = REGISTRY.register("zshjt_chestplate", () -> new ZshjtItem.Chestplate());
	public static final RegistryObject<Item> ZSHJT_LEGGINGS = REGISTRY.register("zshjt_leggings", () -> new ZshjtItem.Leggings());
	public static final RegistryObject<Item> ZSHJT_BOOTS = REGISTRY.register("zshjt_boots", () -> new ZshjtItem.Boots());
	public static final RegistryObject<Item> SZTJ = REGISTRY.register("sztj", () -> new SztjItem());
	public static final RegistryObject<Item> SZZSJ = REGISTRY.register("szzsj", () -> new SzzsjItem());
	public static final RegistryObject<Item> SZHJJ = REGISTRY.register("szhjj", () -> new SzhjjItem());
	public static final RegistryObject<Item> SZSJTIE = REGISTRY.register("szsjtie", () -> new SzsjtieItem());
	public static final RegistryObject<Item> SZZSSJ = REGISTRY.register("szzssj", () -> new SzzssjItem());
	public static final RegistryObject<Item> SZHJSJ = REGISTRY.register("szhjsj", () -> new SzhjsjItem());
	public static final RegistryObject<Item> SZBFZSSHJSJ = REGISTRY.register("szbfzsshjsj", () -> new SzbfzsshjsjItem());
	public static final RegistryObject<Item> SZG = REGISTRY.register("szg", () -> new SzgItem());
	public static final RegistryObject<Item> SZF = REGISTRY.register("szf", () -> new SzfItem());
	public static final RegistryObject<Item> SZQ = REGISTRY.register("szq", () -> new SzqItem());
	public static final RegistryObject<Item> CAOYUANSUECI = block(PrimogemcraftModBlocks.CAOYUANSUECI);
	public static final RegistryObject<Item> SZC = REGISTRY.register("szc", () -> new SzcItem());
	public static final RegistryObject<Item> SZKJTIE_HELMET = REGISTRY.register("szkjtie_helmet", () -> new SzkjtieItem.Helmet());
	public static final RegistryObject<Item> SZKJTIE_CHESTPLATE = REGISTRY.register("szkjtie_chestplate", () -> new SzkjtieItem.Chestplate());
	public static final RegistryObject<Item> SZKJTIE_LEGGINGS = REGISTRY.register("szkjtie_leggings", () -> new SzkjtieItem.Leggings());
	public static final RegistryObject<Item> SZKJTIE_BOOTS = REGISTRY.register("szkjtie_boots", () -> new SzkjtieItem.Boots());
	public static final RegistryObject<Item> SZZSKJ_HELMET = REGISTRY.register("szzskj_helmet", () -> new SzzskjItem.Helmet());
	public static final RegistryObject<Item> SZZSKJ_CHESTPLATE = REGISTRY.register("szzskj_chestplate", () -> new SzzskjItem.Chestplate());
	public static final RegistryObject<Item> SZZSKJ_LEGGINGS = REGISTRY.register("szzskj_leggings", () -> new SzzskjItem.Leggings());
	public static final RegistryObject<Item> SZZSKJ_BOOTS = REGISTRY.register("szzskj_boots", () -> new SzzskjItem.Boots());
	public static final RegistryObject<Item> SZHJKJ_HELMET = REGISTRY.register("szhjkj_helmet", () -> new SzhjkjItem.Helmet());
	public static final RegistryObject<Item> SZHJKJ_CHESTPLATE = REGISTRY.register("szhjkj_chestplate", () -> new SzhjkjItem.Chestplate());
	public static final RegistryObject<Item> SZHJKJ_LEGGINGS = REGISTRY.register("szhjkj_leggings", () -> new SzhjkjItem.Leggings());
	public static final RegistryObject<Item> SZHJKJ_BOOTS = REGISTRY.register("szhjkj_boots", () -> new SzhjkjItem.Boots());
	public static final RegistryObject<Item> DJTSJ = REGISTRY.register("djtsj", () -> new DjtsjItem());
	public static final RegistryObject<Item> DJZSSJ = REGISTRY.register("djzssj", () -> new DjzssjItem());
	public static final RegistryObject<Item> DJHJSJ = REGISTRY.register("djhjsj", () -> new DjhjsjItem());
	public static final RegistryObject<Item> DJZSSHJSJ = REGISTRY.register("djzsshjsj", () -> new DjzsshjsjItem());
	public static final RegistryObject<Item> DJTJ = REGISTRY.register("djtj", () -> new DjtjItem());
	public static final RegistryObject<Item> DDJZSJ = REGISTRY.register("ddjzsj", () -> new DdjzsjItem());
	public static final RegistryObject<Item> DJHJJ = REGISTRY.register("djhjj", () -> new DjhjjItem());
	public static final RegistryObject<Item> DJG = REGISTRY.register("djg", () -> new DjgItem());
	public static final RegistryObject<Item> DJF = REGISTRY.register("djf", () -> new DjfItem());
	public static final RegistryObject<Item> DJQ = REGISTRY.register("djq", () -> new DjqItem());
	public static final RegistryObject<Item> DJC = REGISTRY.register("djc", () -> new DjcItem());
	public static final RegistryObject<Item> QGDYSJ = REGISTRY.register("qgdysj", () -> new QgdysjItem());
	public static final RegistryObject<Item> DJTT_HELMET = REGISTRY.register("djtt_helmet", () -> new DjttItem.Helmet());
	public static final RegistryObject<Item> DJTT_CHESTPLATE = REGISTRY.register("djtt_chestplate", () -> new DjttItem.Chestplate());
	public static final RegistryObject<Item> DJTT_LEGGINGS = REGISTRY.register("djtt_leggings", () -> new DjttItem.Leggings());
	public static final RegistryObject<Item> DJTT_BOOTS = REGISTRY.register("djtt_boots", () -> new DjttItem.Boots());
	public static final RegistryObject<Item> DJZST_HELMET = REGISTRY.register("djzst_helmet", () -> new DjzstItem.Helmet());
	public static final RegistryObject<Item> DJZST_CHESTPLATE = REGISTRY.register("djzst_chestplate", () -> new DjzstItem.Chestplate());
	public static final RegistryObject<Item> DJZST_LEGGINGS = REGISTRY.register("djzst_leggings", () -> new DjzstItem.Leggings());
	public static final RegistryObject<Item> DJZST_BOOTS = REGISTRY.register("djzst_boots", () -> new DjzstItem.Boots());
	public static final RegistryObject<Item> DJHJT_HELMET = REGISTRY.register("djhjt_helmet", () -> new DjhjtItem.Helmet());
	public static final RegistryObject<Item> DJHJT_CHESTPLATE = REGISTRY.register("djhjt_chestplate", () -> new DjhjtItem.Chestplate());
	public static final RegistryObject<Item> DJHJT_LEGGINGS = REGISTRY.register("djhjt_leggings", () -> new DjhjtItem.Leggings());
	public static final RegistryObject<Item> DJHJT_BOOTS = REGISTRY.register("djhjt_boots", () -> new DjhjtItem.Boots());
	public static final RegistryObject<Item> RYTSJ = REGISTRY.register("rytsj", () -> new RytsjItem());
	public static final RegistryObject<Item> RYZSSJ = REGISTRY.register("ryzssj", () -> new RyzssjItem());
	public static final RegistryObject<Item> RYHJSJ = REGISTRY.register("ryhjsj", () -> new RyhjsjItem());
	public static final RegistryObject<Item> RYZSSHJSJ = REGISTRY.register("ryzsshjsj", () -> new RyzsshjsjItem());
	public static final RegistryObject<Item> RYTJ = REGISTRY.register("rytj", () -> new RytjItem());
	public static final RegistryObject<Item> RYZSJ = REGISTRY.register("ryzsj", () -> new RyzsjItem());
	public static final RegistryObject<Item> RYHJJ = REGISTRY.register("ryhjj", () -> new RyhjjItem());
	public static final RegistryObject<Item> RYG = REGISTRY.register("ryg", () -> new RygItem());
	public static final RegistryObject<Item> YSFC = REGISTRY.register("ysfc", () -> new YsfcItem());
	public static final RegistryObject<Item> RYF = REGISTRY.register("ryf", () -> new RyfItem());
	public static final RegistryObject<Item> RYQ = REGISTRY.register("ryq", () -> new RyqItem());
	public static final RegistryObject<Item> RYC = REGISTRY.register("ryc", () -> new RycItem());
	public static final RegistryObject<Item> RYTT_HELMET = REGISTRY.register("rytt_helmet", () -> new RyttItem.Helmet());
	public static final RegistryObject<Item> RYTT_CHESTPLATE = REGISTRY.register("rytt_chestplate", () -> new RyttItem.Chestplate());
	public static final RegistryObject<Item> RYTT_LEGGINGS = REGISTRY.register("rytt_leggings", () -> new RyttItem.Leggings());
	public static final RegistryObject<Item> RYTT_BOOTS = REGISTRY.register("rytt_boots", () -> new RyttItem.Boots());
	public static final RegistryObject<Item> RUZST_HELMET = REGISTRY.register("ruzst_helmet", () -> new RuzstItem.Helmet());
	public static final RegistryObject<Item> RUZST_CHESTPLATE = REGISTRY.register("ruzst_chestplate", () -> new RuzstItem.Chestplate());
	public static final RegistryObject<Item> RUZST_LEGGINGS = REGISTRY.register("ruzst_leggings", () -> new RuzstItem.Leggings());
	public static final RegistryObject<Item> RUZST_BOOTS = REGISTRY.register("ruzst_boots", () -> new RuzstItem.Boots());
	public static final RegistryObject<Item> RYHJT_HELMET = REGISTRY.register("ryhjt_helmet", () -> new RyhjtItem.Helmet());
	public static final RegistryObject<Item> RYHJT_CHESTPLATE = REGISTRY.register("ryhjt_chestplate", () -> new RyhjtItem.Chestplate());
	public static final RegistryObject<Item> RYHJT_LEGGINGS = REGISTRY.register("ryhjt_leggings", () -> new RyhjtItem.Leggings());
	public static final RegistryObject<Item> RYHJT_BOOTS = REGISTRY.register("ryhjt_boots", () -> new RyhjtItem.Boots());
	public static final RegistryObject<Item> AXTSJ = REGISTRY.register("axtsj", () -> new AxtsjItem());
	public static final RegistryObject<Item> AXZSSJ = REGISTRY.register("axzssj", () -> new AxzssjItem());
	public static final RegistryObject<Item> AXHJSJ = REGISTRY.register("axhjsj", () -> new AxhjsjItem());
	public static final RegistryObject<Item> AXZSSHJSJ = REGISTRY.register("axzsshjsj", () -> new AxzsshjsjItem());
	public static final RegistryObject<Item> AXTJ = REGISTRY.register("axtj", () -> new AxtjItem());
	public static final RegistryObject<Item> AXZSJ = REGISTRY.register("axzsj", () -> new AxzsjItem());
	public static final RegistryObject<Item> AXHJJ = REGISTRY.register("axhjj", () -> new AxhjjItem());
	public static final RegistryObject<Item> AXG = REGISTRY.register("axg", () -> new AxgItem());
	public static final RegistryObject<Item> YXAXG = REGISTRY.register("yxaxg", () -> new YxaxgItem());
	public static final RegistryObject<Item> AXF = REGISTRY.register("axf", () -> new AxfItem());
	public static final RegistryObject<Item> AXQ = REGISTRY.register("axq", () -> new AxqItem());
	public static final RegistryObject<Item> AXC = REGISTRY.register("axc", () -> new AxcItem());
	public static final RegistryObject<Item> AXTT_HELMET = REGISTRY.register("axtt_helmet", () -> new AxttItem.Helmet());
	public static final RegistryObject<Item> AXTT_CHESTPLATE = REGISTRY.register("axtt_chestplate", () -> new AxttItem.Chestplate());
	public static final RegistryObject<Item> AXTT_LEGGINGS = REGISTRY.register("axtt_leggings", () -> new AxttItem.Leggings());
	public static final RegistryObject<Item> AXTT_BOOTS = REGISTRY.register("axtt_boots", () -> new AxttItem.Boots());
	public static final RegistryObject<Item> AXZST_HELMET = REGISTRY.register("axzst_helmet", () -> new AxzstItem.Helmet());
	public static final RegistryObject<Item> AXZST_CHESTPLATE = REGISTRY.register("axzst_chestplate", () -> new AxzstItem.Chestplate());
	public static final RegistryObject<Item> AXZST_LEGGINGS = REGISTRY.register("axzst_leggings", () -> new AxzstItem.Leggings());
	public static final RegistryObject<Item> AXZST_BOOTS = REGISTRY.register("axzst_boots", () -> new AxzstItem.Boots());
	public static final RegistryObject<Item> AXHJT_HELMET = REGISTRY.register("axhjt_helmet", () -> new AxhjtItem.Helmet());
	public static final RegistryObject<Item> AXHJT_CHESTPLATE = REGISTRY.register("axhjt_chestplate", () -> new AxhjtItem.Chestplate());
	public static final RegistryObject<Item> AXHJT_LEGGINGS = REGISTRY.register("axhjt_leggings", () -> new AxhjtItem.Leggings());
	public static final RegistryObject<Item> AXHJT_BOOTS = REGISTRY.register("axhjt_boots", () -> new AxhjtItem.Boots());
	public static final RegistryObject<Item> MZSJ = REGISTRY.register("mzsj", () -> new MzsjItem());
	public static final RegistryObject<Item> MZSJ_2 = REGISTRY.register("mzsj_2", () -> new Mzsj2Item());
	public static final RegistryObject<Item> MZSJ_3 = REGISTRY.register("mzsj_3", () -> new Mzsj3Item());
	public static final RegistryObject<Item> QHZLH = REGISTRY.register("qhzlh", () -> new QhzlhItem());
	public static final RegistryObject<Item> QHZLLH_2 = REGISTRY.register("qhzllh_2", () -> new Qhzllh2Item());
	public static final RegistryObject<Item> Q_QU_HANG_ZHOULLH = REGISTRY.register("q_qu_hang_zhoullh", () -> new QQuHangZhoullhItem());
	public static final RegistryObject<Item> MMOLACHUTOU = REGISTRY.register("mmolachutou", () -> new MolachutouItem());
	public static final RegistryObject<Item> ZFG = REGISTRY.register("zfg", () -> new ZfgItem());
	public static final RegistryObject<Item> QWKWZJ = REGISTRY.register("qwkwzj", () -> new QwkwzjItem());
	public static final RegistryObject<Item> SHQWYHDLT = REGISTRY.register("shqwyhdlt", () -> new ShqwyhdltItem());
	public static final RegistryObject<Item> SHQWFNJ = REGISTRY.register("shqwfnj", () -> new ShqwfnjItem());
	public static final RegistryObject<Item> SHCBZX = REGISTRY.register("shcbzx", () -> new ShcbzxItem());
	public static final RegistryObject<Item> XINGJIDALETOU = REGISTRY.register("xingjidaletou", () -> new XingjidaletouItem());
	public static final RegistryObject<Item> SHXJDLT = REGISTRY.register("shxjdlt", () -> new ShxjdltItem());
	public static final RegistryObject<Item> QWTLDHY = REGISTRY.register("qwtldhy", () -> new QwtldhyItem());
	public static final RegistryObject<Item> QWHDLZ = REGISTRY.register("qwhdlz", () -> new QwhdlzItem());
	public static final RegistryObject<Item> JLBJ = REGISTRY.register("jlbj", () -> new JlbjItem());
	public static final RegistryObject<Item> QWYBTZDYPJ = REGISTRY.register("qwybtzdypj", () -> new QwybtzdypjItem());
	public static final RegistryObject<Item> QWXYZQ = REGISTRY.register("qwxyzq", () -> new QwxyzqItem());
	public static final RegistryObject<Item> QWYMZJ = REGISTRY.register("qwymzj", () -> new QwymzjItem());
	public static final RegistryObject<Item> QWFLYB = REGISTRY.register("qwflyb", () -> new QwflybItem());
	public static final RegistryObject<Item> QWXBZSQ = REGISTRY.register("qwxbzsq", () -> new QwxbzsqItem());
	public static final RegistryObject<Item> FENGDANDAIBIAO = REGISTRY.register("fengdandaibiao", () -> new FengdandaibiaoItem());
	public static final RegistryObject<Item> MLXDML_01 = block(PrimogemcraftModBlocks.MLXDML_01);
	public static final RegistryObject<Item> MLXDML_02 = block(PrimogemcraftModBlocks.MLXDML_02);
	public static final RegistryObject<Item> MLXDML_03 = block(PrimogemcraftModBlocks.MLXDML_03);
	public static final RegistryObject<Item> DBMLK = block(PrimogemcraftModBlocks.DBMLK);
	public static final RegistryObject<Item> QHMBML = REGISTRY.register("qhmbml", () -> new QhmbmlItem());
	public static final RegistryObject<Item> QHMBMLYS_01 = REGISTRY.register("qhmbmlys_01", () -> new Qhmbmlys01Item());
	public static final RegistryObject<Item> QHMBMLYS_02 = REGISTRY.register("qhmbmlys_02", () -> new Qhmbmlys02Item());
	public static final RegistryObject<Item> JLZA = REGISTRY.register("jlza", () -> new JlzaItem());
	public static final RegistryObject<Item> JLLIANG = REGISTRY.register("jlliang", () -> new JlliangItem());
	public static final RegistryObject<Item> JLMO = REGISTRY.register("jlmo", () -> new JlmoItem());
	public static final RegistryObject<Item> ZZJS = REGISTRY.register("zzjs", () -> new ZzjsItem());
	public static final RegistryObject<Item> JLZS = REGISTRY.register("jlzs", () -> new JlzsItem());
	public static final RegistryObject<Item> YHJS = REGISTRY.register("yhjs", () -> new YhjsItem());
	public static final RegistryObject<Item> ZHJS = REGISTRY.register("zhjs", () -> new ZhjsItem());
	public static final RegistryObject<Item> ZYJS = REGISTRY.register("zyjs", () -> new ZyjsItem());
	public static final RegistryObject<Item> RYJS = REGISTRY.register("ryjs", () -> new RyjsItem());
	public static final RegistryObject<Item> LIJS = REGISTRY.register("lijs", () -> new LijsItem());
	public static final RegistryObject<Item> ZZJLL = REGISTRY.register("zzjll", () -> new ZzjllItem());
	public static final RegistryObject<Item> JLJSL = REGISTRY.register("jljsl", () -> new JljslItem());
	public static final RegistryObject<Item> YHJSL = REGISTRY.register("yhjsl", () -> new YhjslItem());
	public static final RegistryObject<Item> ZHJSL = REGISTRY.register("zhjsl", () -> new ZhjslItem());
	public static final RegistryObject<Item> ZYJSL = REGISTRY.register("zyjsl", () -> new ZyjslItem());
	public static final RegistryObject<Item> RYJLL = REGISTRY.register("ryjll", () -> new RyjllItem());
	public static final RegistryObject<Item> LAJSL = REGISTRY.register("lajsl", () -> new LajslItem());
	public static final RegistryObject<Item> ZZJSK = block(PrimogemcraftModBlocks.ZZJSK);
	public static final RegistryObject<Item> JLJSK = block(PrimogemcraftModBlocks.JLJSK);
	public static final RegistryObject<Item> YHJSK = block(PrimogemcraftModBlocks.YHJSK);
	public static final RegistryObject<Item> ZHJSK = block(PrimogemcraftModBlocks.ZHJSK);
	public static final RegistryObject<Item> ZYJSK = block(PrimogemcraftModBlocks.ZYJSK);
	public static final RegistryObject<Item> RYJSK = block(PrimogemcraftModBlocks.RYJSK);
	public static final RegistryObject<Item> LAJSK = block(PrimogemcraftModBlocks.LAJSK);
	public static final RegistryObject<Item> DANGAOLIYUE = block(PrimogemcraftModBlocks.DANGAOLIYUE);
	public static final RegistryObject<Item> YSJBFPK = REGISTRY.register("ysjbfpk", () -> new YsjbfpkItem());
	public static final RegistryObject<Item> LJTG_01 = REGISTRY.register("ljtg_01", () -> new Ljtg01Item());
	public static final RegistryObject<Item> LJTG_02 = REGISTRY.register("ljtg_02", () -> new Ljtg02Item());
	public static final RegistryObject<Item> XZCFYXWZD = REGISTRY.register("xzcfyxwzd", () -> new XzcfyxwzdItem());
	public static final RegistryObject<Item> CHUNMEIZHIPAO = REGISTRY.register("chunmeizhipao", () -> new ChunmeizhipaoItem());
	public static final RegistryObject<Item> QWJZYJ = REGISTRY.register("qwjzyj", () -> new QwjzyjItem());
	public static final RegistryObject<Item> XJHPYHFH = block(PrimogemcraftModBlocks.XJHPYHFH);
	public static final RegistryObject<Item> CUNQUPINGZHENG = REGISTRY.register("cunqupingzheng", () -> new CunqupingzhengItem());
	public static final RegistryObject<Item> JDYK = block(PrimogemcraftModBlocks.JDYK);
	public static final RegistryObject<Item> BWDXJHPYHFH = block(PrimogemcraftModBlocks.BWDXJHPYHFH);
	public static final RegistryObject<Item> YISHIJIECUNZHE = REGISTRY.register("yishijiecunzhe", () -> new YishijiecunzheItem());
	public static final RegistryObject<Item> HQFENG = REGISTRY.register("hqfeng", () -> new HqfengItem());
	public static final RegistryObject<Item> HQYAN = REGISTRY.register("hqyan", () -> new HqyanItem());
	public static final RegistryObject<Item> HQLEI = REGISTRY.register("hqlei", () -> new HqleiItem());
	public static final RegistryObject<Item> HQCAO = REGISTRY.register("hqcao", () -> new HqcaoItem());
	public static final RegistryObject<Item> HQSHUI = REGISTRY.register("hqshui", () -> new HqshuiItem());
	public static final RegistryObject<Item> HQHUO = REGISTRY.register("hqhuo", () -> new HqhuoItem());
	public static final RegistryObject<Item> HQBING = REGISTRY.register("hqbing", () -> new HqbingItem());
	public static final RegistryObject<Item> MLJNB = REGISTRY.register("mljnb", () -> new MljnbItem());
	public static final RegistryObject<Item> QWYZZM = REGISTRY.register("qwyzzm", () -> new QwyzzmItem());
	public static final RegistryObject<Item> JIANSHIJINGBAN = block(PrimogemcraftModBlocks.JIANSHIJINGBAN);
	public static final RegistryObject<Item> SHIWUTSSLM = REGISTRY.register("shiwutsslm", () -> new ShiwutsslmItem());
	public static final RegistryObject<Item> CUKUANGKONGYUE = REGISTRY.register("cukuangkongyue", () -> new CukuangkongyueItem());
	public static final RegistryObject<Item> CUKUANGCHIYUE = REGISTRY.register("cukuangchiyue", () -> new CukuangchiyueItem());
	public static final RegistryObject<Item> CUKUANGMANYUE = REGISTRY.register("cukuangmanyue", () -> new CukuangmanyueItem());
	public static final RegistryObject<Item> QIWUHEISENLINGGZ = REGISTRY.register("qiwuheisenlinggz", () -> new QiwuheisenlinggzItem());
	public static final RegistryObject<Item> QWGGZFENLIE_A = REGISTRY.register("qwggzfenlie_a", () -> new QwggzfenlieAItem());
	public static final RegistryObject<Item> QWGGZFENLIE_B = REGISTRY.register("qwggzfenlie_b", () -> new QwggzfenlieBItem());
	public static final RegistryObject<Item> TESHUKUIJIA_01_HELMET = REGISTRY.register("teshukuijia_01_helmet", () -> new Teshukuijia01Item.Helmet());
	public static final RegistryObject<Item> TESHUKUIJIA_01_CHESTPLATE = REGISTRY.register("teshukuijia_01_chestplate", () -> new Teshukuijia01Item.Chestplate());
	public static final RegistryObject<Item> TESHUKUIJIA_01_LEGGINGS = REGISTRY.register("teshukuijia_01_leggings", () -> new Teshukuijia01Item.Leggings());
	public static final RegistryObject<Item> TESHUKUIJIA_01_BOOTS = REGISTRY.register("teshukuijia_01_boots", () -> new Teshukuijia01Item.Boots());
	public static final RegistryObject<Item> GUZHONGLINGJIAN = REGISTRY.register("guzhonglingjian", () -> new GuzhonglingjianItem());
	public static final RegistryObject<Item> YDGGZ = REGISTRY.register("ydggz", () -> new YdggzItem());
	public static final RegistryObject<Item> SHENMILIHE = REGISTRY.register("shenmilihe", () -> new ShenmiliheItem());
	public static final RegistryObject<Item> QHZLLH_4 = REGISTRY.register("qhzllh_4", () -> new Qhzllh4Item());
	public static final RegistryObject<Item> HUALIDUANZAO = block(PrimogemcraftModBlocks.HUALIDUANZAO);
	public static final RegistryObject<Item> QWTCJLBPTBG = REGISTRY.register("qwtcjlbptbg", () -> new QwtcjlbptbgItem());
	public static final RegistryObject<Item> QWLBTDGCL = REGISTRY.register("qwlbtdgcl", () -> new QwlbtdgclItem());
	public static final RegistryObject<Item> QUXGJIBING = REGISTRY.register("quxgjibing", () -> new QuxgjibingItem());
	public static final RegistryObject<Item> QWQCXXMX = REGISTRY.register("qwqcxxmx", () -> new QwqcxxmxItem());
	public static final RegistryObject<Item> QWWXNTDMJ = REGISTRY.register("qwwxntdmj", () -> new QwwxntdmjItem());
	public static final RegistryObject<Item> GZSMZ = REGISTRY.register("gzsmz", () -> new GzsmzItem());
	public static final RegistryObject<Item> QWQSKXJXT = REGISTRY.register("qwqskxjxt", () -> new QwqskxjxtItem());
	public static final RegistryObject<Item> QWSMCL = REGISTRY.register("qwsmcl", () -> new QwsmclItem());
	public static final RegistryObject<Item> SH_JWUPIN = REGISTRY.register("sh_jwupin", () -> new SHJwupinItem());
	public static final RegistryObject<Item> SJBCQ = REGISTRY.register("sjbcq", () -> new SjbcqItem());
	public static final RegistryObject<Item> HHZD_0 = block(PrimogemcraftModBlocks.HHZD_0);
	public static final RegistryObject<Item> HHZD_1 = block(PrimogemcraftModBlocks.HHZD_1);
	public static final RegistryObject<Item> SHENMIWANOU = block(PrimogemcraftModBlocks.SHENMIWANOU);
	public static final RegistryObject<Item> HHZDBOO = block(PrimogemcraftModBlocks.HHZDBOO);
	public static final RegistryObject<Item> HHYINBAOQI = block(PrimogemcraftModBlocks.HHYINBAOQI);
	public static final RegistryObject<Item> YSJFR = REGISTRY.register("ysjfr", () -> new YsjfrItem());
	public static final RegistryObject<Item> YSSP = REGISTRY.register("yssp", () -> new YsspItem());
	public static final RegistryObject<Item> SUIJIWUPIN = REGISTRY.register("suijiwupin", () -> new SuijiwupinItem());
	public static final RegistryObject<Item> YUANSHIF = REGISTRY.register("yuanshif", () -> new YuanshifItem());
	public static final RegistryObject<Item> YSJTSJ_0 = block(PrimogemcraftModBlocks.YSJTSJ_0);
	public static final RegistryObject<Item> YSJTSJ_1 = block(PrimogemcraftModBlocks.YSJTSJ_1);
	public static final RegistryObject<Item> MLLP = REGISTRY.register("mllp", () -> new MllpItem());
	public static final RegistryObject<Item> MLLPWZ = REGISTRY.register("mllpwz", () -> new MllpwzItem());
	public static final RegistryObject<Item> MLLPZS = REGISTRY.register("mllpzs", () -> new MllpzsItem());
	public static final RegistryObject<Item> MLLPHJ = REGISTRY.register("mllphj", () -> new MllphjItem());
	public static final RegistryObject<Item> ZSSP = REGISTRY.register("zssp", () -> new ZsspItem());
	public static final RegistryObject<Item> YHDLTYIDIE = REGISTRY.register("yhdltyidie", () -> new YhdltyidieItem());
	public static final RegistryObject<Item> YDFMS = REGISTRY.register("ydfms", () -> new YdfmsItem());
	public static final RegistryObject<Item> YSRZ_0 = REGISTRY.register("ysrz_0", () -> new Ysrz0Item());
	public static final RegistryObject<Item> YSRQSP = REGISTRY.register("ysrqsp", () -> new YsrqspItem());
	public static final RegistryObject<Item> YSRZSPSX = REGISTRY.register("ysrzspsx", () -> new YsrzspsxItem());
	public static final RegistryObject<Item> QYCX = REGISTRY.register("qycx", () -> new QycxItem());
	public static final RegistryObject<Item> QYHX = REGISTRY.register("qyhx", () -> new QyhxItem());
	public static final RegistryObject<Item> QYHXSHILIAN = REGISTRY.register("qyhxshilian", () -> new QyhxshilianItem());

	// Start of user code block custom items
	// End of user code block custom items
	private static RegistryObject<Item> block(RegistryObject<Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties()));
	}

	@SubscribeEvent
	public static void clientLoad(FMLClientSetupEvent event) {
		event.enqueueWork(() -> {
			ItemProperties.register(MMOLA_01.get(), new ResourceLocation("primogemcraft:mmola_01_shuliang"),
					(itemStackToRender, clientWorld, entity, itemEntityId) -> (float) Yssp_sxProcedure.execute(entity != null ? entity.level() : clientWorld, itemStackToRender));
			ItemProperties.register(LJTG_01.get(), new ResourceLocation("blocking"), ItemProperties.getProperty(Items.SHIELD, new ResourceLocation("blocking")));
			ItemProperties.register(LJTG_02.get(), new ResourceLocation("blocking"), ItemProperties.getProperty(Items.SHIELD, new ResourceLocation("blocking")));
			ItemProperties.register(XZCFYXWZD.get(), new ResourceLocation("blocking"), ItemProperties.getProperty(Items.SHIELD, new ResourceLocation("blocking")));
			ItemProperties.register(SJBCQ.get(), new ResourceLocation("primogemcraft:sjbcq_pinzhi"), (itemStackToRender, clientWorld, entity, itemEntityId) -> (float) FumoquanpinzhizhiProcedure.execute(itemStackToRender));
			ItemProperties.register(YSSP.get(), new ResourceLocation("primogemcraft:yssp_shuliang"),
					(itemStackToRender, clientWorld, entity, itemEntityId) -> (float) Yssp_sxProcedure.execute(entity != null ? entity.level() : clientWorld, itemStackToRender));
			ItemProperties.register(ZSSP.get(), new ResourceLocation("primogemcraft:zssp_shuliang"),
					(itemStackToRender, clientWorld, entity, itemEntityId) -> (float) Yssp_sxProcedure.execute(entity != null ? entity.level() : clientWorld, itemStackToRender));
			ItemProperties.register(YHDLTYIDIE.get(), new ResourceLocation("primogemcraft:yhdltyidie_shuliang"), (itemStackToRender, clientWorld, entity, itemEntityId) -> (float) YdyhdltsxProcedure.execute(itemStackToRender));
			ItemProperties.register(YSRZ_0.get(), new ResourceLocation("primogemcraft:ysrz_0_feng"), (itemStackToRender, clientWorld, entity, itemEntityId) -> (float) Ysrqa0Procedure.execute(itemStackToRender));
			ItemProperties.register(YSRZ_0.get(), new ResourceLocation("primogemcraft:ysrz_0_yan"), (itemStackToRender, clientWorld, entity, itemEntityId) -> (float) Ysrqa1Procedure.execute(itemStackToRender));
			ItemProperties.register(YSRZ_0.get(), new ResourceLocation("primogemcraft:ysrz_0_lei"), (itemStackToRender, clientWorld, entity, itemEntityId) -> (float) Ysrqa2Procedure.execute(itemStackToRender));
			ItemProperties.register(YSRZ_0.get(), new ResourceLocation("primogemcraft:ysrz_0_cao"), (itemStackToRender, clientWorld, entity, itemEntityId) -> (float) Ysrqa3Procedure.execute(itemStackToRender));
			ItemProperties.register(YSRZ_0.get(), new ResourceLocation("primogemcraft:ysrz_0_shui"), (itemStackToRender, clientWorld, entity, itemEntityId) -> (float) Ysrqa4Procedure.execute(itemStackToRender));
			ItemProperties.register(YSRZ_0.get(), new ResourceLocation("primogemcraft:ysrz_0_huo"), (itemStackToRender, clientWorld, entity, itemEntityId) -> (float) Ysrqa5Procedure.execute(itemStackToRender));
			ItemProperties.register(YSRQSP.get(), new ResourceLocation("primogemcraft:ysrqsp_shu"),
					(itemStackToRender, clientWorld, entity, itemEntityId) -> (float) Yssp_sxProcedure.execute(entity != null ? entity.level() : clientWorld, itemStackToRender));
		});
	}
}
